import { Difficulty, DietType, Unit } from '@prisma/client';

// Type definitions for recipe creation
type IngredientInput = {
    name: string;
    quantity: number;
    unit: Unit;
    optional?: boolean;
};

type RecipeInput = {
    title: string;
    slug: string;
    description: string;
    prepTime: number;
    cookTime: number;
    difficulty: Difficulty;
    servings?: number;
    tags: string[];
    toolsRequired: string[];
    dietTypes: DietType[];
    ingredients: IngredientInput[];
    steps: Array<{ stepNumber: number; instruction: string }>;
    calories?: number;
    carbohydrates?: number;
    fats?: number;
    proteins?: number;
    fibers?: number;
};

// Extended recipes collection - A LOT of recipes!
export const extendedRecipes: RecipeInput[] = [
    // === RECETTES FRANÇAISES CLASSIQUES ===
    {
        title: 'Coq au Vin',
        slug: 'coq-au-vin',
        description: 'Plat traditionnel français au vin rouge, cuisses de poulet mijotées avec des champignons',
        prepTime: 20,
        cookTime: 90,
        difficulty: Difficulty.MEDIUM,
        servings: 4,
        tags: ['french', 'classic', 'comfort_food'],
        toolsRequired: ['casserole'],
        dietTypes: [],
        calories: 420,
        carbohydrates: 18,
        fats: 15,
        proteins: 35,
        fibers: 2,
        ingredients: [
            { name: 'poulet', quantity: 800, unit: Unit.G },
            { name: 'vin rouge', quantity: 500, unit: Unit.ML },
            { name: 'champignon', quantity: 200, unit: Unit.G },
            { name: 'oignon', quantity: 2, unit: Unit.PIECE },
            { name: 'carotte', quantity: 2, unit: Unit.PIECE },
            { name: 'lardons', quantity: 100, unit: Unit.G },
            { name: 'beurre', quantity: 30, unit: Unit.G },
            { name: 'farine', quantity: 20, unit: Unit.G },
            { name: 'bouillon de poulet', quantity: 250, unit: Unit.ML },
            { name: 'thym', quantity: 1, unit: Unit.TSP },
            { name: 'laurier', quantity: 2, unit: Unit.PIECE },
            { name: 'sel', quantity: 1, unit: Unit.PINCH },
            { name: 'poivre', quantity: 1, unit: Unit.PINCH },
        ],
        steps: [
            { stepNumber: 1, instruction: 'Découper le poulet en morceaux et les faire revenir dans le beurre jusqu\'à coloration.' },
            { stepNumber: 2, instruction: 'Ajouter les lardons, oignons et carottes coupés, faire revenir 5 minutes.' },
            { stepNumber: 3, instruction: 'Saupoudrer de farine, mélanger puis verser le vin rouge et le bouillon.' },
            { stepNumber: 4, instruction: 'Ajouter le thym et le laurier, saler et poivrer. Laisser mijoter 1h15 à feu doux.' },
            { stepNumber: 5, instruction: 'Ajouter les champignons 15 minutes avant la fin. Servir chaud.' },
        ],
    },
    {
        title: 'Bœuf Bourguignon',
        slug: 'boeuf-bourguignon',
        description: 'Ragoût de bœuf mijoté au vin rouge bourguignon avec des légumes',
        prepTime: 30,
        cookTime: 180,
        difficulty: Difficulty.MEDIUM,
        servings: 6,
        tags: ['french', 'classic', 'comfort_food', 'sunday_roast'],
        toolsRequired: ['casserole', 'oven'],
        dietTypes: [],
        calories: 485,
        carbohydrates: 22,
        fats: 18,
        proteins: 42,
        fibers: 3,
        ingredients: [
            { name: 'boeuf haché', quantity: 1200, unit: Unit.G },
            { name: 'vin rouge', quantity: 750, unit: Unit.ML },
            { name: 'champignon', quantity: 300, unit: Unit.G },
            { name: 'oignon', quantity: 3, unit: Unit.PIECE },
            { name: 'carotte', quantity: 4, unit: Unit.PIECE },
            { name: 'lardons', quantity: 150, unit: Unit.G },
            { name: 'tomate concassée', quantity: 200, unit: Unit.G },
            { name: 'bouillon de légumes', quantity: 500, unit: Unit.ML },
            { name: 'farine', quantity: 30, unit: Unit.G },
            { name: 'beurre', quantity: 40, unit: Unit.G },
            { name: 'thym', quantity: 2, unit: Unit.TSP },
            { name: 'laurier', quantity: 3, unit: Unit.PIECE },
            { name: 'ail', quantity: 3, unit: Unit.CLOVE },
            { name: 'sel', quantity: 1, unit: Unit.PINCH },
            { name: 'poivre', quantity: 1, unit: Unit.PINCH },
        ],
        steps: [
            { stepNumber: 1, instruction: 'Couper la viande en gros cubes de 4-5 cm. Les faire revenir dans le beurre jusqu\'à coloration sur toutes les faces.' },
            { stepNumber: 2, instruction: 'Retirer la viande, faire revenir les lardons, puis les oignons et carottes coupés en morceaux.' },
            { stepNumber: 3, instruction: 'Remettre la viande, saupoudrer de farine, bien mélanger puis ajouter le vin et le bouillon.' },
            { stepNumber: 4, instruction: 'Ajouter la tomate concassée, l\'ail écrasé, le thym et le laurier. Saler et poivrer.' },
            { stepNumber: 5, instruction: 'Couvrir et laisser mijoter au four à 160°C pendant 2h30.' },
            { stepNumber: 6, instruction: 'Ajouter les champignons entiers 30 minutes avant la fin. Servir très chaud.' },
        ],
    },
    {
        title: 'Ratatouille',
        slug: 'ratatouille',
        description: 'Mélange de légumes provençaux mijotés, plat emblématique du sud de la France',
        prepTime: 30,
        cookTime: 60,
        difficulty: Difficulty.EASY,
        servings: 4,
        tags: ['french', 'vegetarian', 'healthy'],
        toolsRequired: ['casserole'],
        dietTypes: [DietType.VEGETARIAN, DietType.VEGAN],
        calories: 125,
        carbohydrates: 18,
        fats: 6,
        proteins: 3,
        fibers: 6,
        ingredients: [
            { name: 'aubergine', quantity: 2, unit: Unit.PIECE },
            { name: 'courgette', quantity: 2, unit: Unit.PIECE },
            { name: 'poivron', quantity: 2, unit: Unit.PIECE },
            { name: 'tomate', quantity: 4, unit: Unit.PIECE },
            { name: 'oignon', quantity: 2, unit: Unit.PIECE },
            { name: 'ail', quantity: 3, unit: Unit.CLOVE },
            { name: 'huile d\'olive', quantity: 4, unit: Unit.TBSP },
            { name: 'herbes de provence', quantity: 2, unit: Unit.TSP },
            { name: 'basilic', quantity: 0.5, unit: Unit.BUNCH },
            { name: 'sel', quantity: 1, unit: Unit.PINCH },
            { name: 'poivre', quantity: 1, unit: Unit.PINCH },
        ],
        steps: [
            { stepNumber: 1, instruction: 'Couper tous les légumes en dés réguliers d\'environ 2 cm.' },
            { stepNumber: 2, instruction: 'Faire revenir les oignons et l\'ail dans l\'huile d\'olive 5 minutes.' },
            { stepNumber: 3, instruction: 'Ajouter les aubergines et courgettes, faire revenir 10 minutes.' },
            { stepNumber: 4, instruction: 'Ajouter les poivrons et les tomates, les herbes de Provence, saler et poivrer.' },
            { stepNumber: 5, instruction: 'Couvrir et laisser mijoter à feu doux 40 minutes en remuant de temps en temps.' },
            { stepNumber: 6, instruction: 'Ajouter le basilic ciselé en fin de cuisson. Servir chaud ou froid.' },
        ],
    },
    {
        title: 'Tarte Tatin',
        slug: 'tarte-tatin',
        description: 'Tarte aux pommes renversée, spécialité française traditionnelle',
        prepTime: 45,
        cookTime: 45,
        difficulty: Difficulty.HARD,
        servings: 8,
        tags: ['french', 'classic'],
        toolsRequired: ['oven'],
        dietTypes: [DietType.VEGETARIAN],
        calories: 285,
        carbohydrates: 42,
        fats: 12,
        proteins: 3,
        fibers: 3,
        ingredients: [
            { name: 'pomme', quantity: 8, unit: Unit.PIECE },
            { name: 'pâte feuilletée', quantity: 1, unit: Unit.PIECE },
            { name: 'sucre', quantity: 100, unit: Unit.G },
            { name: 'beurre', quantity: 60, unit: Unit.G },
            { name: 'vanille', quantity: 1, unit: Unit.TSP },
        ],
        steps: [
            { stepNumber: 1, instruction: 'Préchauffer le four à 200°C. Peler et couper les pommes en quartiers.' },
            { stepNumber: 2, instruction: 'Faire fondre le beurre dans une poêle allant au four, ajouter le sucre jusqu\'à caramélisation.' },
            { stepNumber: 3, instruction: 'Disposer les pommes en rosace dans le caramel, cuire 15 minutes.' },
            { stepNumber: 4, instruction: 'Recouvrir avec la pâte feuilletée, enfoncer les bords. Cuire 30 minutes au four.' },
            { stepNumber: 5, instruction: 'Démouler immédiatement à la sortie du four. Servir tiède.' },
        ],
    },

    // === RECETTES ITALIENNES ===
    {
        title: 'Risotto aux Champignons',
        slug: 'risotto-aux-champignons',
        description: 'Risotto crémeux aux champignons, spécialité italienne',
        prepTime: 15,
        cookTime: 30,
        difficulty: Difficulty.MEDIUM,
        servings: 4,
        tags: ['italian', 'vegetarian', 'comfort_food'],
        toolsRequired: ['casserole'],
        dietTypes: [DietType.VEGETARIAN],
        calories: 320,
        carbohydrates: 55,
        fats: 8,
        proteins: 10,
        fibers: 2,
        ingredients: [
            { name: 'riz', quantity: 350, unit: Unit.G },
            { name: 'champignon', quantity: 300, unit: Unit.G },
            { name: 'oignon', quantity: 1, unit: Unit.PIECE },
            { name: 'bouillon de légumes', quantity: 1000, unit: Unit.ML },
            { name: 'vin blanc', quantity: 100, unit: Unit.ML },
            { name: 'parmesan', quantity: 50, unit: Unit.G },
            { name: 'beurre', quantity: 40, unit: Unit.G },
            { name: 'huile d\'olive', quantity: 2, unit: Unit.TBSP },
            { name: 'ail', quantity: 2, unit: Unit.CLOVE },
            { name: 'persil', quantity: 0.25, unit: Unit.BUNCH },
            { name: 'sel', quantity: 1, unit: Unit.PINCH },
            { name: 'poivre', quantity: 1, unit: Unit.PINCH },
        ],
        steps: [
            { stepNumber: 1, instruction: 'Faire chauffer le bouillon dans une casserole. Faire revenir les champignons dans l\'huile d\'olive avec l\'ail.' },
            { stepNumber: 2, instruction: 'Dans une grande casserole, faire revenir l\'oignon émincé dans le beurre jusqu\'à transparence.' },
            { stepNumber: 3, instruction: 'Ajouter le riz, remuer 2 minutes jusqu\'à nacré. Verser le vin blanc et laisser évaporer.' },
            { stepNumber: 4, instruction: 'Ajouter le bouillon louche par louche en remuant constamment jusqu\'à absorption.' },
            { stepNumber: 5, instruction: 'Quand le riz est crémeux (18-20 min), ajouter les champignons, le parmesan et le persil. Servir immédiatement.' },
        ],
    },
    {
        title: 'Lasagnes Maison',
        slug: 'lasagnes-maison',
        description: 'Lasagnes à la bolognaise traditionnelles, gratinées au fromage',
        prepTime: 45,
        cookTime: 60,
        difficulty: Difficulty.HARD,
        servings: 6,
        tags: ['italian', 'classic', 'comfort_food', 'family'],
        toolsRequired: ['casserole', 'oven'],
        dietTypes: [],
        calories: 520,
        carbohydrates: 45,
        fats: 22,
        proteins: 32,
        fibers: 4,
        ingredients: [
            { name: 'pâtes', quantity: 400, unit: Unit.G },
            { name: 'boeuf haché', quantity: 600, unit: Unit.G },
            { name: 'tomate concassée', quantity: 500, unit: Unit.G },
            { name: 'oignon', quantity: 2, unit: Unit.PIECE },
            { name: 'ail', quantity: 3, unit: Unit.CLOVE },
            { name: 'fromage râpé', quantity: 200, unit: Unit.G },
            { name: 'mozzarella', quantity: 200, unit: Unit.G },
            { name: 'beurre', quantity: 50, unit: Unit.G },
            { name: 'farine', quantity: 50, unit: Unit.G },
            { name: 'lait', quantity: 500, unit: Unit.ML },
            { name: 'huile d\'olive', quantity: 2, unit: Unit.TBSP },
            { name: 'basilic', quantity: 0.5, unit: Unit.BUNCH },
            { name: 'sel', quantity: 1, unit: Unit.PINCH },
            { name: 'poivre', quantity: 1, unit: Unit.PINCH },
        ],
        steps: [
            { stepNumber: 1, instruction: 'Faire revenir l\'oignon et l\'ail dans l\'huile. Ajouter la viande et faire revenir jusqu\'à cuisson.' },
            { stepNumber: 2, instruction: 'Ajouter la tomate concassée, le basilic, saler et poivrer. Laisser mijoter 30 minutes.' },
            { stepNumber: 3, instruction: 'Faire la béchamel : faire fondre le beurre, ajouter la farine, puis le lait progressivement en fouettant.' },
            { stepNumber: 4, instruction: 'Dans un plat, alterner couches de pâtes, bolognaise, béchamel et fromage râpé.' },
            { stepNumber: 5, instruction: 'Terminer par de la béchamel et du fromage. Cuire au four à 180°C pendant 40 minutes.' },
        ],
    },
    {
        title: 'Spaghetti Carbonara',
        slug: 'spaghetti-carbonara',
        description: 'Spaghetti à la carbonara authentique, crémeuse et savoureuse',
        prepTime: 10,
        cookTime: 15,
        difficulty: Difficulty.EASY,
        servings: 4,
        tags: ['italian', 'quick', 'comfort_food'],
        toolsRequired: ['casserole'],
        dietTypes: [],
        calories: 485,
        carbohydrates: 65,
        fats: 18,
        proteins: 22,
        fibers: 3,
        ingredients: [
            { name: 'pâtes', quantity: 400, unit: Unit.G },
            { name: 'lardons', quantity: 200, unit: Unit.G },
            { name: 'oeuf', quantity: 4, unit: Unit.PIECE },
            { name: 'parmesan', quantity: 100, unit: Unit.G },
            { name: 'poivre', quantity: 2, unit: Unit.PINCH },
            { name: 'sel', quantity: 1, unit: Unit.PINCH },
        ],
        steps: [
            { stepNumber: 1, instruction: 'Faire cuire les pâtes dans une grande quantité d\'eau salée.' },
            { stepNumber: 2, instruction: 'Pendant ce temps, faire revenir les lardons dans une poêle jusqu\'à ce qu\'ils soient croustillants.' },
            { stepNumber: 3, instruction: 'Battre les œufs avec le parmesan râpé et beaucoup de poivre noir.' },
            { stepNumber: 4, instruction: 'Égoutter les pâtes en gardant un peu d\'eau de cuisson, les remettre dans la casserole chaude.' },
            { stepNumber: 5, instruction: 'Hors du feu, ajouter les lardons puis le mélange œufs-parmesan en remuant rapidement. Servir immédiatement.' },
        ],
    },
    {
        title: 'Penne all\'Arrabbiata',
        slug: 'penne-arrabbiata',
        description: 'Pâtes épicées à la sauce tomate, spécialité romaine',
        prepTime: 5,
        cookTime: 15,
        difficulty: Difficulty.EASY,
        servings: 4,
        tags: ['italian', 'quick', 'spicy', 'vegetarian'],
        toolsRequired: ['casserole'],
        dietTypes: [DietType.VEGETARIAN, DietType.VEGAN],
        calories: 295,
        carbohydrates: 58,
        fats: 6,
        proteins: 10,
        fibers: 4,
        ingredients: [
            { name: 'pâtes', quantity: 400, unit: Unit.G },
            { name: 'tomate concassée', quantity: 500, unit: Unit.G },
            { name: 'ail', quantity: 4, unit: Unit.CLOVE },
            { name: 'huile d\'olive', quantity: 4, unit: Unit.TBSP },
            { name: 'piment', quantity: 2, unit: Unit.PIECE },
            { name: 'persil', quantity: 0.25, unit: Unit.BUNCH },
            { name: 'sel', quantity: 1, unit: Unit.PINCH },
        ],
        steps: [
            { stepNumber: 1, instruction: 'Faire cuire les pâtes dans l\'eau salée bouillante.' },
            { stepNumber: 2, instruction: 'Dans une poêle, faire chauffer l\'huile d\'olive avec l\'ail émincé et le piment coupé.' },
            { stepNumber: 3, instruction: 'Ajouter les tomates concassées, saler et laisser mijoter 10 minutes.' },
            { stepNumber: 4, instruction: 'Égoutter les pâtes et les mélanger avec la sauce. Parsemer de persil et servir.' },
        ],
    },

    // === RECETTES VÉGÉTARIENNES/VÉGÉTALIENNES ===
    {
        title: 'Curry de Légumes',
        slug: 'curry-legumes',
        description: 'Curry végétarien aux légumes et lait de coco',
        prepTime: 20,
        cookTime: 30,
        difficulty: Difficulty.EASY,
        servings: 4,
        tags: ['vegetarian', 'healthy', 'indian'],
        toolsRequired: ['casserole'],
        dietTypes: [DietType.VEGETARIAN, DietType.VEGAN],
        calories: 185,
        carbohydrates: 28,
        fats: 7,
        proteins: 5,
        fibers: 6,
        ingredients: [
            { name: 'courgette', quantity: 2, unit: Unit.PIECE },
            { name: 'aubergine', quantity: 1, unit: Unit.PIECE },
            { name: 'poivron', quantity: 2, unit: Unit.PIECE },
            { name: 'tomate', quantity: 3, unit: Unit.PIECE },
            { name: 'oignon', quantity: 2, unit: Unit.PIECE },
            { name: 'lait de coco', quantity: 400, unit: Unit.ML },
            { name: 'curry', quantity: 2, unit: Unit.TSP },
            { name: 'cumin', quantity: 1, unit: Unit.TSP },
            { name: 'ail', quantity: 3, unit: Unit.CLOVE },
            { name: 'huile d\'olive', quantity: 3, unit: Unit.TBSP },
            { name: 'coriandre', quantity: 0.25, unit: Unit.BUNCH },
            { name: 'sel', quantity: 1, unit: Unit.PINCH },
        ],
        steps: [
            { stepNumber: 1, instruction: 'Couper tous les légumes en morceaux. Faire revenir l\'oignon et l\'ail dans l\'huile.' },
            { stepNumber: 2, instruction: 'Ajouter les épices (curry, cumin) et faire revenir 1 minute jusqu\'à parfumées.' },
            { stepNumber: 3, instruction: 'Ajouter les légumes et les faire revenir 5 minutes en remuant.' },
            { stepNumber: 4, instruction: 'Verser le lait de coco, saler et laisser mijoter 20 minutes jusqu\'à ce que les légumes soient tendres.' },
            { stepNumber: 5, instruction: 'Ajouter la coriandre ciselée. Servir avec du riz.' },
        ],
    },
    {
        title: 'Salade de Quinoa aux Légumes',
        slug: 'salade-quinoa-legumes',
        description: 'Salade complète au quinoa avec légumes croquants',
        prepTime: 15,
        cookTime: 15,
        difficulty: Difficulty.EASY,
        servings: 4,
        tags: ['vegetarian', 'healthy', 'quick'],
        toolsRequired: ['casserole'],
        dietTypes: [DietType.VEGETARIAN, DietType.VEGAN],
        calories: 220,
        carbohydrates: 38,
        fats: 6,
        proteins: 8,
        fibers: 5,
        ingredients: [
            { name: 'quinoa', quantity: 200, unit: Unit.G },
            { name: 'tomate', quantity: 3, unit: Unit.PIECE },
            { name: 'concombre', quantity: 1, unit: Unit.PIECE },
            { name: 'poivron', quantity: 1, unit: Unit.PIECE },
            { name: 'oignon', quantity: 0.5, unit: Unit.PIECE },
            { name: 'citron', quantity: 1, unit: Unit.PIECE },
            { name: 'huile d\'olive', quantity: 3, unit: Unit.TBSP },
            { name: 'persil', quantity: 0.25, unit: Unit.BUNCH },
            { name: 'menthe', quantity: 0.25, unit: Unit.BUNCH },
            { name: 'sel', quantity: 1, unit: Unit.PINCH },
            { name: 'poivre', quantity: 1, unit: Unit.PINCH },
        ],
        steps: [
            { stepNumber: 1, instruction: 'Faire cuire le quinoa selon les instructions (15 minutes dans l\'eau bouillante).' },
            { stepNumber: 2, instruction: 'Laisser refroidir le quinoa. Couper tous les légumes en petits dés.' },
            { stepNumber: 3, instruction: 'Mélanger le quinoa froid avec tous les légumes.' },
            { stepNumber: 4, instruction: 'Préparer la vinaigrette avec le jus de citron, l\'huile d\'olive, le sel et le poivre.' },
            { stepNumber: 5, instruction: 'Verser la vinaigrette sur la salade, ajouter les herbes ciselées et mélanger.' },
        ],
    },
    {
        title: 'Burger Végétarien',
        slug: 'burger-vegetarien',
        description: 'Burger aux légumes et légumineuses, savoureux et nutritif',
        prepTime: 25,
        cookTime: 15,
        difficulty: Difficulty.MEDIUM,
        servings: 4,
        tags: ['vegetarian', 'healthy'],
        toolsRequired: ['oven'],
        dietTypes: [DietType.VEGETARIAN, DietType.VEGAN],
        calories: 285,
        carbohydrates: 42,
        fats: 9,
        proteins: 12,
        fibers: 8,
        ingredients: [
            { name: 'pois chiches', quantity: 400, unit: Unit.G },
            { name: 'carotte', quantity: 2, unit: Unit.PIECE },
            { name: 'oignon', quantity: 1, unit: Unit.PIECE },
            { name: 'ail', quantity: 2, unit: Unit.CLOVE },
            { name: 'farine', quantity: 50, unit: Unit.G },
            { name: 'cumin', quantity: 1, unit: Unit.TSP },
            { name: 'paprika', quantity: 1, unit: Unit.TSP },
            { name: 'pain', quantity: 4, unit: Unit.SLICE },
            { name: 'salade', quantity: 0.25, unit: Unit.BUNCH },
            { name: 'tomate', quantity: 1, unit: Unit.PIECE },
            { name: 'huile d\'olive', quantity: 3, unit: Unit.TBSP },
            { name: 'sel', quantity: 1, unit: Unit.PINCH },
        ],
        steps: [
            { stepNumber: 1, instruction: 'Égoutter et rincer les pois chiches. Les écraser grossièrement à la fourchette.' },
            { stepNumber: 2, instruction: 'Râper les carottes, émincer l\'oignon et l\'ail finement.' },
            { stepNumber: 3, instruction: 'Mélanger pois chiches, légumes, farine, épices et sel. Former 4 galettes.' },
            { stepNumber: 4, instruction: 'Faire cuire les galettes au four à 180°C pendant 15 minutes, retourner à mi-cuisson.' },
            { stepNumber: 5, instruction: 'Servir dans le pain avec la salade et les tomates en rondelles.' },
        ],
    },

    // === RECETTES RAPIDES ===
    {
        title: 'Wrap au Poulet',
        slug: 'wrap-poulet',
        description: 'Wrap rapide au poulet et légumes frais',
        prepTime: 10,
        cookTime: 10,
        difficulty: Difficulty.EASY,
        servings: 2,
        tags: ['quick', 'healthy'],
        toolsRequired: [],
        dietTypes: [],
        calories: 385,
        carbohydrates: 45,
        fats: 12,
        proteins: 28,
        fibers: 4,
        ingredients: [
            { name: 'poulet', quantity: 200, unit: Unit.G },
            { name: 'tortilla', quantity: 2, unit: Unit.PIECE },
            { name: 'salade', quantity: 0.25, unit: Unit.BUNCH },
            { name: 'tomate', quantity: 1, unit: Unit.PIECE },
            { name: 'yaourt', quantity: 50, unit: Unit.G },
            { name: 'citron', quantity: 0.5, unit: Unit.PIECE },
            { name: 'sel', quantity: 1, unit: Unit.PINCH },
            { name: 'poivre', quantity: 1, unit: Unit.PINCH },
        ],
        steps: [
            { stepNumber: 1, instruction: 'Couper le poulet en lamelles et le faire revenir 8-10 minutes jusqu\'à cuisson.' },
            { stepNumber: 2, instruction: 'Préparer la sauce : mélanger le yaourt avec le jus de citron, saler et poivrer.' },
            { stepNumber: 3, instruction: 'Chauffer les tortillas 30 secondes au micro-ondes ou dans une poêle.' },
            { stepNumber: 4, instruction: 'Garnir les tortillas avec la salade, les tomates, le poulet et la sauce.' },
            { stepNumber: 5, instruction: 'Rouler les wraps et servir immédiatement.' },
        ],
    },
    {
        title: 'Omelette Espagnole',
        slug: 'omelette-espagnole',
        description: 'Omelette aux pommes de terre et oignons, version espagnole',
        prepTime: 15,
        cookTime: 25,
        difficulty: Difficulty.EASY,
        servings: 4,
        tags: ['quick', 'vegetarian'],
        toolsRequired: ['casserole'],
        dietTypes: [DietType.VEGETARIAN],
        calories: 245,
        carbohydrates: 28,
        fats: 10,
        proteins: 12,
        fibers: 3,
        ingredients: [
            { name: 'oeuf', quantity: 6, unit: Unit.PIECE },
            { name: 'pomme de terre', quantity: 500, unit: Unit.G },
            { name: 'oignon', quantity: 1, unit: Unit.PIECE },
            { name: 'huile d\'olive', quantity: 4, unit: Unit.TBSP },
            { name: 'sel', quantity: 1, unit: Unit.PINCH },
            { name: 'poivre', quantity: 1, unit: Unit.PINCH },
        ],
        steps: [
            { stepNumber: 1, instruction: 'Éplucher et couper les pommes de terre en fines rondelles.' },
            { stepNumber: 2, instruction: 'Faire cuire les pommes de terre dans l\'huile d\'olive avec l\'oignon émincé pendant 20 minutes à feu moyen.' },
            { stepNumber: 3, instruction: 'Battre les œufs dans un bol, saler et poivrer.' },
            { stepNumber: 4, instruction: 'Verser les œufs sur les pommes de terre, laisser cuire 3-4 minutes puis retourner l\'omelette.' },
            { stepNumber: 5, instruction: 'Cuire l\'autre face 2-3 minutes. Servir chaud ou froid.' },
        ],
    },
    {
        title: 'Sandwich Club',
        slug: 'sandwich-club',
        description: 'Sandwich triple étage au poulet, bacon et légumes',
        prepTime: 10,
        cookTime: 5,
        difficulty: Difficulty.EASY,
        servings: 2,
        tags: ['quick'],
        toolsRequired: [],
        dietTypes: [],
        calories: 520,
        carbohydrates: 48,
        fats: 22,
        proteins: 32,
        fibers: 3,
        ingredients: [
            { name: 'pain', quantity: 6, unit: Unit.SLICE },
            { name: 'poulet', quantity: 150, unit: Unit.G },
            { name: 'lardons', quantity: 50, unit: Unit.G },
            { name: 'tomate', quantity: 1, unit: Unit.PIECE },
            { name: 'salade', quantity: 0.25, unit: Unit.BUNCH },
            { name: 'mayonnaise', quantity: 2, unit: Unit.TBSP },
            { name: 'sel', quantity: 1, unit: Unit.PINCH },
            { name: 'poivre', quantity: 1, unit: Unit.PINCH },
        ],
        steps: [
            { stepNumber: 1, instruction: 'Griller les lardons jusqu\'à croustillants. Faire cuire le poulet et le couper en tranches.' },
            { stepNumber: 2, instruction: 'Toaster les tranches de pain légèrement.' },
            { stepNumber: 3, instruction: 'Tartiner de mayonnaise 3 tranches de pain.' },
            { stepNumber: 4, instruction: 'Sur la première tranche : salade, tomate, poulet. Couvrir avec la deuxième tranche.' },
            { stepNumber: 5, instruction: 'Sur la deuxième : salade, lardons. Couvrir avec la troisième tranche. Couper en diagonale et servir.' },
        ],
    },

    // === RECETTES SANTÉ ===
    {
        title: 'Saumon en Papillote',
        slug: 'saumon-papillote',
        description: 'Filet de saumon cuit en papillote avec légumes, sain et délicieux',
        prepTime: 15,
        cookTime: 20,
        difficulty: Difficulty.EASY,
        servings: 2,
        tags: ['healthy', 'fish', 'quick'],
        toolsRequired: ['oven'],
        dietTypes: [DietType.PESCATARIAN],
        calories: 285,
        carbohydrates: 8,
        fats: 12,
        proteins: 35,
        fibers: 3,
        ingredients: [
            { name: 'saumon', quantity: 400, unit: Unit.G },
            { name: 'courgette', quantity: 1, unit: Unit.PIECE },
            { name: 'carotte', quantity: 1, unit: Unit.PIECE },
            { name: 'citron', quantity: 1, unit: Unit.PIECE },
            { name: 'aneth', quantity: 0.25, unit: Unit.BUNCH },
            { name: 'huile d\'olive', quantity: 2, unit: Unit.TBSP },
            { name: 'sel', quantity: 1, unit: Unit.PINCH },
            { name: 'poivre', quantity: 1, unit: Unit.PINCH },
        ],
        steps: [
            { stepNumber: 1, instruction: 'Préchauffer le four à 200°C. Découper du papier sulfurisé en rectangles.' },
            { stepNumber: 2, instruction: 'Couper les légumes en julienne fine.' },
            { stepNumber: 3, instruction: 'Disposer les légumes au centre du papier, poser le saumon dessus.' },
            { stepNumber: 4, instruction: 'Arroser d\'huile d\'olive et de jus de citron, ajouter l\'aneth, saler et poivrer.' },
            { stepNumber: 5, instruction: 'Fermer la papillote hermétiquement. Cuire 15-20 minutes au four. Servir dans la papillote.' },
        ],
    },
    {
        title: 'Bowl de Poulet et Légumes',
        slug: 'bowl-poulet-legumes',
        description: 'Bowl équilibré avec poulet grillé, légumes et céréales',
        prepTime: 20,
        cookTime: 20,
        difficulty: Difficulty.EASY,
        servings: 2,
        tags: ['healthy', 'quick'],
        toolsRequired: ['oven'],
        dietTypes: [],
        calories: 385,
        carbohydrates: 42,
        fats: 10,
        proteins: 32,
        fibers: 6,
        ingredients: [
            { name: 'poulet', quantity: 300, unit: Unit.G },
            { name: 'riz', quantity: 150, unit: Unit.G },
            { name: 'brocoli', quantity: 200, unit: Unit.G },
            { name: 'carotte', quantity: 2, unit: Unit.PIECE },
            { name: 'courgette', quantity: 1, unit: Unit.PIECE },
            { name: 'huile d\'olive', quantity: 2, unit: Unit.TBSP },
            { name: 'citron', quantity: 1, unit: Unit.PIECE },
            { name: 'ail', quantity: 2, unit: Unit.CLOVE },
            { name: 'sel', quantity: 1, unit: Unit.PINCH },
            { name: 'poivre', quantity: 1, unit: Unit.PINCH },
        ],
        steps: [
            { stepNumber: 1, instruction: 'Faire cuire le riz selon les instructions.' },
            { stepNumber: 2, instruction: 'Couper le poulet en dés et le faire mariner avec l\'ail, le citron, l\'huile, sel et poivre 10 minutes.' },
            { stepNumber: 3, instruction: 'Faire cuire le poulet dans une poêle 10-12 minutes jusqu\'à doré.' },
            { stepNumber: 4, instruction: 'Cuire les légumes à la vapeur ou les faire revenir rapidement.' },
            { stepNumber: 5, instruction: 'Disposer le riz, les légumes et le poulet dans des bols. Arroser de jus de citron et servir.' },
        ],
    },
    {
        title: 'Soupe de Légumes',
        slug: 'soupe-legumes',
        description: 'Soupe réconfortante aux légumes de saison',
        prepTime: 15,
        cookTime: 30,
        difficulty: Difficulty.EASY,
        servings: 4,
        tags: ['healthy', 'soup', 'vegetarian'],
        toolsRequired: ['casserole'],
        dietTypes: [DietType.VEGETARIAN, DietType.VEGAN],
        calories: 85,
        carbohydrates: 15,
        fats: 2,
        proteins: 3,
        fibers: 5,
        ingredients: [
            { name: 'carotte', quantity: 3, unit: Unit.PIECE },
            { name: 'courgette', quantity: 2, unit: Unit.PIECE },
            { name: 'pomme de terre', quantity: 300, unit: Unit.G },
            { name: 'poireau', quantity: 2, unit: Unit.PIECE },
            { name: 'oignon', quantity: 1, unit: Unit.PIECE },
            { name: 'bouillon de légumes', quantity: 1000, unit: Unit.ML },
            { name: 'huile d\'olive', quantity: 2, unit: Unit.TBSP },
            { name: 'persil', quantity: 0.25, unit: Unit.BUNCH },
            { name: 'sel', quantity: 1, unit: Unit.PINCH },
            { name: 'poivre', quantity: 1, unit: Unit.PINCH },
        ],
        steps: [
            { stepNumber: 1, instruction: 'Éplucher et couper tous les légumes en morceaux.' },
            { stepNumber: 2, instruction: 'Faire revenir l\'oignon dans l\'huile d\'olive jusqu\'à transparence.' },
            { stepNumber: 3, instruction: 'Ajouter tous les légumes et faire revenir 5 minutes.' },
            { stepNumber: 4, instruction: 'Verser le bouillon, saler et poivrer. Laisser mijoter 25 minutes.' },
            { stepNumber: 5, instruction: 'Mixer ou laisser en morceaux selon préférence. Ajouter le persil et servir chaud.' },
        ],
    },

    // === RECETTES POISSONS ===
    {
        title: 'Poisson au Four aux Herbes',
        slug: 'poisson-four-herbes',
        description: 'Filet de poisson blanc cuit au four avec herbes et citron',
        prepTime: 10,
        cookTime: 20,
        difficulty: Difficulty.EASY,
        servings: 2,
        tags: ['fish', 'healthy', 'quick'],
        toolsRequired: ['oven'],
        dietTypes: [DietType.PESCATARIAN],
        calories: 220,
        carbohydrates: 2,
        fats: 8,
        proteins: 32,
        fibers: 0,
        ingredients: [
            { name: 'cabillaud', quantity: 400, unit: Unit.G },
            { name: 'citron', quantity: 1, unit: Unit.PIECE },
            { name: 'aneth', quantity: 0.25, unit: Unit.BUNCH },
            { name: 'persil', quantity: 0.25, unit: Unit.BUNCH },
            { name: 'huile d\'olive', quantity: 2, unit: Unit.TBSP },
            { name: 'ail', quantity: 2, unit: Unit.CLOVE },
            { name: 'sel', quantity: 1, unit: Unit.PINCH },
            { name: 'poivre', quantity: 1, unit: Unit.PINCH },
        ],
        steps: [
            { stepNumber: 1, instruction: 'Préchauffer le four à 180°C.' },
            { stepNumber: 2, instruction: 'Mélanger l\'huile d\'olive avec l\'ail émincé et les herbes ciselées.' },
            { stepNumber: 3, instruction: 'Disposer le poisson dans un plat allant au four.' },
            { stepNumber: 4, instruction: 'Arroser du mélange huile-herbes, ajouter des rondelles de citron, saler et poivrer.' },
            { stepNumber: 5, instruction: 'Cuire 15-20 minutes selon l\'épaisseur du poisson. Servir avec du citron.' },
        ],
    },
    {
        title: 'Crevettes à l\'Ail',
        slug: 'crevettes-ail',
        description: 'Crevettes sautées à l\'ail et au persil, simple et délicieux',
        prepTime: 10,
        cookTime: 5,
        difficulty: Difficulty.EASY,
        servings: 2,
        tags: ['fish', 'quick'],
        toolsRequired: ['casserole'],
        dietTypes: [DietType.PESCATARIAN],
        calories: 185,
        carbohydrates: 3,
        fats: 8,
        proteins: 24,
        fibers: 0,
        ingredients: [
            { name: 'crevettes', quantity: 300, unit: Unit.G },
            { name: 'ail', quantity: 4, unit: Unit.CLOVE },
            { name: 'persil', quantity: 0.5, unit: Unit.BUNCH },
            { name: 'citron', quantity: 1, unit: Unit.PIECE },
            { name: 'huile d\'olive', quantity: 3, unit: Unit.TBSP },
            { name: 'beurre', quantity: 20, unit: Unit.G },
            { name: 'sel', quantity: 1, unit: Unit.PINCH },
            { name: 'poivre', quantity: 1, unit: Unit.PINCH },
        ],
        steps: [
            { stepNumber: 1, instruction: 'Décortiquer les crevettes si nécessaire. Émincer finement l\'ail et hacher le persil.' },
            { stepNumber: 2, instruction: 'Faire chauffer l\'huile et le beurre dans une grande poêle à feu vif.' },
            { stepNumber: 3, instruction: 'Ajouter l\'ail et faire revenir 30 secondes sans brûler.' },
            { stepNumber: 4, instruction: 'Ajouter les crevettes et faire cuire 2-3 minutes de chaque côté jusqu\'à rosées.' },
            { stepNumber: 5, instruction: 'Ajouter le persil, le jus de citron, saler et poivrer. Servir immédiatement.' },
        ],
    },

    // === RECETTES PLATS UNIQUES ===
    {
        title: 'Chili Con Carne',
        slug: 'chili-con-carne',
        description: 'Chili épicé à la viande et aux haricots rouges',
        prepTime: 20,
        cookTime: 60,
        difficulty: Difficulty.MEDIUM,
        servings: 6,
        tags: ['comfort_food', 'spicy', 'one_pot'],
        toolsRequired: ['casserole'],
        dietTypes: [],
        calories: 385,
        carbohydrates: 35,
        fats: 15,
        proteins: 28,
        fibers: 10,
        ingredients: [
            { name: 'boeuf haché', quantity: 600, unit: Unit.G },
            { name: 'haricots rouges', quantity: 400, unit: Unit.G },
            { name: 'tomate concassée', quantity: 500, unit: Unit.G },
            { name: 'oignon', quantity: 2, unit: Unit.PIECE },
            { name: 'ail', quantity: 3, unit: Unit.CLOVE },
            { name: 'piment', quantity: 2, unit: Unit.PIECE },
            { name: 'cumin', quantity: 2, unit: Unit.TSP },
            { name: 'paprika', quantity: 1, unit: Unit.TSP },
            { name: 'huile d\'olive', quantity: 2, unit: Unit.TBSP },
            { name: 'bouillon de légumes', quantity: 250, unit: Unit.ML },
            { name: 'sel', quantity: 1, unit: Unit.PINCH },
        ],
        steps: [
            { stepNumber: 1, instruction: 'Faire revenir l\'oignon et l\'ail dans l\'huile jusqu\'à transparence.' },
            { stepNumber: 2, instruction: 'Ajouter la viande et faire revenir jusqu\'à ce qu\'elle soit bien cuite.' },
            { stepNumber: 3, instruction: 'Ajouter les épices (cumin, paprika, piment) et remuer 1 minute.' },
            { stepNumber: 4, instruction: 'Ajouter les tomates concassées, les haricots égouttés et le bouillon.' },
            { stepNumber: 5, instruction: 'Laisser mijoter 45 minutes à feu doux en remuant de temps en temps. Servir chaud.' },
        ],
    },
    {
        title: 'Tajine de Poulet',
        slug: 'tajine-poulet',
        description: 'Tajine marocain au poulet, citron confit et olives',
        prepTime: 30,
        cookTime: 75,
        difficulty: Difficulty.MEDIUM,
        servings: 4,
        tags: ['comfort_food', 'one_pot'],
        toolsRequired: ['casserole'],
        dietTypes: [DietType.HALAL],
        calories: 425,
        carbohydrates: 25,
        fats: 18,
        proteins: 38,
        fibers: 4,
        ingredients: [
            { name: 'poulet', quantity: 1000, unit: Unit.G },
            { name: 'oignon', quantity: 2, unit: Unit.PIECE },
            { name: 'citron confit', quantity: 2, unit: Unit.PIECE },
            { name: 'olives', quantity: 100, unit: Unit.G },
            { name: 'gingembre', quantity: 20, unit: Unit.G },
            { name: 'curry', quantity: 1, unit: Unit.TSP },
            { name: 'cumin', quantity: 1, unit: Unit.TSP },
            { name: 'coriandre', quantity: 0.5, unit: Unit.BUNCH },
            { name: 'bouillon de poulet', quantity: 500, unit: Unit.ML },
            { name: 'huile d\'olive', quantity: 3, unit: Unit.TBSP },
            { name: 'sel', quantity: 1, unit: Unit.PINCH },
        ],
        steps: [
            { stepNumber: 1, instruction: 'Faire revenir le poulet coupé en morceaux dans l\'huile jusqu\'à coloration.' },
            { stepNumber: 2, instruction: 'Ajouter les oignons émincés et le gingembre râpé, faire revenir 5 minutes.' },
            { stepNumber: 3, instruction: 'Ajouter les épices (curry, cumin) et remuer jusqu\'à parfumées.' },
            { stepNumber: 4, instruction: 'Verser le bouillon, ajouter les citrons confits et les olives. Couvrir et laisser mijoter 1 heure.' },
            { stepNumber: 5, instruction: 'Ajouter la coriandre ciselée en fin de cuisson. Servir avec du couscous.' },
        ],
    },
    {
        title: 'Pad Thaï',
        slug: 'pad-thai',
        description: 'Nouilles de riz sautées aux crevettes, spécialité thaïlandaise',
        prepTime: 20,
        cookTime: 15,
        difficulty: Difficulty.MEDIUM,
        servings: 2,
        tags: ['quick', 'spicy', 'fish'],
        toolsRequired: ['casserole'],
        dietTypes: [DietType.PESCATARIAN],
        calories: 485,
        carbohydrates: 72,
        fats: 12,
        proteins: 22,
        fibers: 3,
        ingredients: [
            { name: 'nouilles de riz', quantity: 200, unit: Unit.G },
            { name: 'crevettes', quantity: 200, unit: Unit.G },
            { name: 'oeuf', quantity: 2, unit: Unit.PIECE },
            { name: 'pousses de soja', quantity: 100, unit: Unit.G },
            { name: 'ciboulette', quantity: 0.25, unit: Unit.BUNCH },
            { name: 'sauce soja', quantity: 3, unit: Unit.TBSP },
            { name: 'citron', quantity: 1, unit: Unit.PIECE },
            { name: 'huile d\'olive', quantity: 3, unit: Unit.TBSP },
            { name: 'sucre', quantity: 1, unit: Unit.TBSP },
            { name: 'piment', quantity: 1, unit: Unit.PIECE },
        ],
        steps: [
            { stepNumber: 1, instruction: 'Tremper les nouilles dans l\'eau chaude 10 minutes jusqu\'à souples.' },
            { stepNumber: 2, instruction: 'Faire revenir les crevettes dans l\'huile 3-4 minutes, réserver.' },
            { stepNumber: 3, instruction: 'Battre les œufs et les faire brouiller dans la même poêle, réserver.' },
            { stepNumber: 4, instruction: 'Faire sauter les nouilles égouttées avec la sauce soja et le sucre.' },
            { stepNumber: 5, instruction: 'Remettre crevettes et œufs, ajouter les pousses de soja et la ciboulette. Servir avec citron et piment.' },
        ],
    },

    // === RECETTES DESSERTS ===
    {
        title: 'Tiramisu',
        slug: 'tiramisu',
        description: 'Dessert italien au café et mascarpone, classique et élégant',
        prepTime: 30,
        cookTime: 0,
        difficulty: Difficulty.MEDIUM,
        servings: 8,
        tags: ['italian', 'classic'],
        toolsRequired: [],
        dietTypes: [DietType.VEGETARIAN],
        calories: 285,
        carbohydrates: 25,
        fats: 18,
        proteins: 6,
        fibers: 0,
        ingredients: [
            { name: 'mascarpone', quantity: 500, unit: Unit.G },
            { name: 'oeuf', quantity: 4, unit: Unit.PIECE },
            { name: 'sucre', quantity: 80, unit: Unit.G },
            { name: 'café fort', quantity: 250, unit: Unit.ML },
            { name: 'biscuits à la cuillère', quantity: 24, unit: Unit.PIECE },
            { name: 'cacao', quantity: 20, unit: Unit.G },
        ],
        steps: [
            { stepNumber: 1, instruction: 'Séparer les jaunes des blancs d\'œufs. Battre les jaunes avec le sucre jusqu\'à blanchiment.' },
            { stepNumber: 2, instruction: 'Ajouter le mascarpone aux jaunes et mélanger délicatement.' },
            { stepNumber: 3, instruction: 'Battre les blancs en neige ferme et les incorporer délicatement au mélange.' },
            { stepNumber: 4, instruction: 'Tremper rapidement les biscuits dans le café froid.' },
            { stepNumber: 5, instruction: 'Disposer une couche de biscuits, puis une couche de crème, répéter. Réserver au frais 4h minimum. Saupoudrer de cacao avant de servir.' },
        ],
    },
    {
        title: 'Brownies au Chocolat',
        slug: 'brownies-chocolat',
        description: 'Brownies moelleux et fondants au chocolat noir',
        prepTime: 15,
        cookTime: 25,
        difficulty: Difficulty.EASY,
        servings: 12,
        tags: ['classic'],
        toolsRequired: ['oven'],
        dietTypes: [DietType.VEGETARIAN],
        calories: 320,
        carbohydrates: 38,
        fats: 18,
        proteins: 4,
        fibers: 2,
        ingredients: [
            { name: 'chocolat noir', quantity: 200, unit: Unit.G },
            { name: 'beurre', quantity: 150, unit: Unit.G },
            { name: 'sucre', quantity: 200, unit: Unit.G },
            { name: 'oeuf', quantity: 3, unit: Unit.PIECE },
            { name: 'farine', quantity: 80, unit: Unit.G },
            { name: 'noix', quantity: 100, unit: Unit.G },
        ],
        steps: [
            { stepNumber: 1, instruction: 'Préchauffer le four à 180°C. Faire fondre le chocolat avec le beurre au bain-marie.' },
            { stepNumber: 2, instruction: 'Dans un saladier, battre les œufs avec le sucre jusqu\'à ce que le mélange blanchisse.' },
            { stepNumber: 3, instruction: 'Incorporer le chocolat fondu, puis la farine et les noix concassées.' },
            { stepNumber: 4, instruction: 'Verser dans un moule carré beurré et enfourner 20-25 minutes.' },
            { stepNumber: 5, instruction: 'Laisser refroidir avant de couper en carrés.' },
        ],
    },

    // === RECETTES PETIT-DÉJEUNER ===
    {
        title: 'Pancakes',
        slug: 'pancakes',
        description: 'Pancakes moelleux américains, parfaits pour le petit-déjeuner',
        prepTime: 10,
        cookTime: 15,
        difficulty: Difficulty.EASY,
        servings: 4,
        tags: ['quick'],
        toolsRequired: ['casserole'],
        dietTypes: [DietType.VEGETARIAN],
        calories: 245,
        carbohydrates: 38,
        fats: 8,
        proteins: 6,
        fibers: 1,
        ingredients: [
            { name: 'farine', quantity: 200, unit: Unit.G },
            { name: 'lait', quantity: 250, unit: Unit.ML },
            { name: 'oeuf', quantity: 1, unit: Unit.PIECE },
            { name: 'beurre', quantity: 30, unit: Unit.G },
            { name: 'sucre', quantity: 30, unit: Unit.G },
            { name: 'levure', quantity: 10, unit: Unit.G },
            { name: 'sel', quantity: 0.5, unit: Unit.PINCH },
        ],
        steps: [
            { stepNumber: 1, instruction: 'Mélanger la farine, le sucre, la levure et le sel dans un saladier.' },
            { stepNumber: 2, instruction: 'Dans un autre récipient, battre l\'œuf avec le lait et le beurre fondu.' },
            { stepNumber: 3, instruction: 'Verser le mélange liquide dans la farine et mélanger jusqu\'à obtenir une pâte lisse.' },
            { stepNumber: 4, instruction: 'Faire chauffer une poêle huilée. Verser une louche de pâte et cuire 2 minutes de chaque côté.' },
            { stepNumber: 5, instruction: 'Servir chaud avec du sirop d\'érable, du miel ou des fruits.' },
        ],
    },
    {
        title: 'Porridge aux Fruits',
        slug: 'porridge-fruits',
        description: 'Porridge crémeux aux fruits, petit-déjeuner sain et rassasiant',
        prepTime: 5,
        cookTime: 10,
        difficulty: Difficulty.EASY,
        servings: 2,
        tags: ['healthy', 'quick', 'vegetarian'],
        toolsRequired: ['casserole'],
        dietTypes: [DietType.VEGETARIAN, DietType.VEGAN],
        calories: 285,
        carbohydrates: 58,
        fats: 5,
        proteins: 8,
        fibers: 6,
        ingredients: [
            { name: 'flocons d\'avoine', quantity: 100, unit: Unit.G },
            { name: 'lait', quantity: 400, unit: Unit.ML },
            { name: 'banane', quantity: 1, unit: Unit.PIECE },
            { name: 'miel', quantity: 2, unit: Unit.TBSP },
            { name: 'noix', quantity: 30, unit: Unit.G },
        ],
        steps: [
            { stepNumber: 1, instruction: 'Faire chauffer le lait dans une casserole.' },
            { stepNumber: 2, instruction: 'Ajouter les flocons d\'avoine et cuire 8-10 minutes en remuant jusqu\'à crémeux.' },
            { stepNumber: 3, instruction: 'Couper la banane en rondelles.' },
            { stepNumber: 4, instruction: 'Servir le porridge chaud avec la banane, le miel et les noix concassées.' },
        ],
    },

    // === RECETTES BATCH COOKING ===
    {
        title: 'Bolognaise en Grande Quantité',
        slug: 'bolognaise-grande-quantite',
        description: 'Sauce bolognaise à préparer en grande quantité pour plusieurs repas',
        prepTime: 30,
        cookTime: 120,
        difficulty: Difficulty.MEDIUM,
        servings: 12,
        tags: ['batch_cooking', 'italian', 'comfort_food'],
        toolsRequired: ['casserole'],
        dietTypes: [],
        calories: 285,
        carbohydrates: 18,
        fats: 15,
        proteins: 22,
        fibers: 3,
        ingredients: [
            { name: 'boeuf haché', quantity: 1500, unit: Unit.G },
            { name: 'tomate concassée', quantity: 1500, unit: Unit.G },
            { name: 'oignon', quantity: 4, unit: Unit.PIECE },
            { name: 'carotte', quantity: 4, unit: Unit.PIECE },
            { name: 'céleri', quantity: 3, unit: Unit.PIECE },
            { name: 'ail', quantity: 6, unit: Unit.CLOVE },
            { name: 'vin rouge', quantity: 250, unit: Unit.ML },
            { name: 'bouillon de légumes', quantity: 500, unit: Unit.ML },
            { name: 'huile d\'olive', quantity: 4, unit: Unit.TBSP },
            { name: 'basilic', quantity: 1, unit: Unit.BUNCH },
            { name: 'sel', quantity: 1, unit: Unit.PINCH },
            { name: 'poivre', quantity: 1, unit: Unit.PINCH },
        ],
        steps: [
            { stepNumber: 1, instruction: 'Couper finement oignon, carottes et céleri. Faire revenir dans l\'huile jusqu\'à tendres.' },
            { stepNumber: 2, instruction: 'Ajouter l\'ail émincé et la viande, faire revenir jusqu\'à cuisson complète.' },
            { stepNumber: 3, instruction: 'Verser le vin et laisser réduire de moitié.' },
            { stepNumber: 4, instruction: 'Ajouter les tomates, le bouillon, le basilic, saler et poivrer. Laisser mijoter 1h30 à feu doux.' },
            { stepNumber: 5, instruction: 'Laisser refroidir et diviser en portions pour congélation ou conservation au réfrigérateur.' },
        ],
    },
    {
        title: 'Curry de Poulet en Grande Quantité',
        slug: 'curry-poulet-grande-quantite',
        description: 'Curry de poulet à préparer en grande quantité pour plusieurs repas',
        prepTime: 25,
        cookTime: 45,
        difficulty: Difficulty.MEDIUM,
        servings: 10,
        tags: ['batch_cooking', 'indian', 'spicy'],
        toolsRequired: ['casserole'],
        dietTypes: [DietType.HALAL],
        calories: 320,
        carbohydrates: 12,
        fats: 16,
        proteins: 32,
        fibers: 2,
        ingredients: [
            { name: 'poulet', quantity: 2000, unit: Unit.G },
            { name: 'oignon', quantity: 4, unit: Unit.PIECE },
            { name: 'tomate', quantity: 6, unit: Unit.PIECE },
            { name: 'lait de coco', quantity: 800, unit: Unit.ML },
            { name: 'curry', quantity: 3, unit: Unit.TSP },
            { name: 'cumin', quantity: 2, unit: Unit.TSP },
            { name: 'coriandre en poudre', quantity: 2, unit: Unit.TSP },
            { name: 'gingembre', quantity: 40, unit: Unit.G },
            { name: 'ail', quantity: 6, unit: Unit.CLOVE },
            { name: 'huile d\'olive', quantity: 4, unit: Unit.TBSP },
            { name: 'coriandre', quantity: 1, unit: Unit.BUNCH },
            { name: 'sel', quantity: 1, unit: Unit.PINCH },
        ],
        steps: [
            { stepNumber: 1, instruction: 'Couper le poulet en morceaux. Faire revenir dans l\'huile jusqu\'à coloration, réserver.' },
            { stepNumber: 2, instruction: 'Dans la même casserole, faire revenir les oignons, l\'ail et le gingembre râpé 5 minutes.' },
            { stepNumber: 3, instruction: 'Ajouter toutes les épices et remuer 1 minute jusqu\'à parfumées.' },
            { stepNumber: 4, instruction: 'Ajouter les tomates concassées, remettre le poulet, verser le lait de coco.' },
            { stepNumber: 5, instruction: 'Laisser mijoter 35 minutes. Ajouter la coriandre fraîche. Diviser en portions pour conservation.' },
        ],
    },
];

