import { IngredientCategory, Unit } from '@prisma/client';

// Extended ingredients collection - A LOT of ingredients!
export const extendedIngredients = [
    // === LÉGUMES FRAIS SUPPLÉMENTAIRES ===
    { name: 'asperge', category: IngredientCategory.FRESH, defaultUnit: Unit.PIECE },
    { name: 'artichaut', category: IngredientCategory.FRESH, defaultUnit: Unit.PIECE },
    { name: 'avocat', category: IngredientCategory.FRESH, defaultUnit: Unit.PIECE },
    { name: 'betterave', category: IngredientCategory.FRESH, defaultUnit: Unit.PIECE },
    { name: 'blette', category: IngredientCategory.FRESH, defaultUnit: Unit.BUNCH },
    { name: 'chou', category: IngredientCategory.FRESH, defaultUnit: Unit.PIECE },
    { name: 'chou de Bruxelles', category: IngredientCategory.FRESH, defaultUnit: Unit.G },
    { name: 'chou rouge', category: IngredientCategory.FRESH, defaultUnit: Unit.PIECE },
    { name: 'chou kale', category: IngredientCategory.FRESH, defaultUnit: Unit.BUNCH },
    { name: 'concombre', category: IngredientCategory.FRESH, defaultUnit: Unit.PIECE },
    { name: 'cornichon', category: IngredientCategory.FRESH, defaultUnit: Unit.G },
    { name: 'courge', category: IngredientCategory.FRESH, defaultUnit: Unit.PIECE },
    { name: 'potiron', category: IngredientCategory.FRESH, defaultUnit: Unit.PIECE },
    { name: 'butternut', category: IngredientCategory.FRESH, defaultUnit: Unit.PIECE },
    { name: 'endive', category: IngredientCategory.FRESH, defaultUnit: Unit.PIECE },
    { name: 'fenouil', category: IngredientCategory.FRESH, defaultUnit: Unit.PIECE },
    { name: 'haricot vert', category: IngredientCategory.FRESH, defaultUnit: Unit.G },
    { name: 'navet', category: IngredientCategory.FRESH, defaultUnit: Unit.PIECE },
    { name: 'panais', category: IngredientCategory.FRESH, defaultUnit: Unit.PIECE },
    { name: 'patate douce', category: IngredientCategory.FRESH, defaultUnit: Unit.G },
    { name: 'radis', category: IngredientCategory.FRESH, defaultUnit: Unit.PIECE },
    { name: 'rutabaga', category: IngredientCategory.FRESH, defaultUnit: Unit.PIECE },
    { name: 'topinambour', category: IngredientCategory.FRESH, defaultUnit: Unit.G },
    { name: 'cresson', category: IngredientCategory.FRESH, defaultUnit: Unit.BUNCH },
    { name: 'roquette', category: IngredientCategory.FRESH, defaultUnit: Unit.BUNCH },
    { name: 'mâche', category: IngredientCategory.FRESH, defaultUnit: Unit.BUNCH },
    { name: 'mesclun', category: IngredientCategory.FRESH, defaultUnit: Unit.BUNCH },
    { name: 'chicorée', category: IngredientCategory.FRESH, defaultUnit: Unit.PIECE },
    { name: 'laitue', category: IngredientCategory.FRESH, defaultUnit: Unit.PIECE },
    { name: 'scarole', category: IngredientCategory.FRESH, defaultUnit: Unit.PIECE },
    { name: 'épinard frais', category: IngredientCategory.FRESH, defaultUnit: Unit.BUNCH },
    { name: 'blette', category: IngredientCategory.FRESH, defaultUnit: Unit.BUNCH },
    { name: 'bette à carde', category: IngredientCategory.FRESH, defaultUnit: Unit.BUNCH },
    { name: 'pak choi', category: IngredientCategory.FRESH, defaultUnit: Unit.PIECE },
    { name: 'chou chinois', category: IngredientCategory.FRESH, defaultUnit: Unit.PIECE },
    { name: 'daikon', category: IngredientCategory.FRESH, defaultUnit: Unit.PIECE },

    // === FRUITS ===
    { name: 'pomme', category: IngredientCategory.FRESH, defaultUnit: Unit.PIECE },
    { name: 'poire', category: IngredientCategory.FRESH, defaultUnit: Unit.PIECE },
    { name: 'banane', category: IngredientCategory.FRESH, defaultUnit: Unit.PIECE },
    { name: 'orange', category: IngredientCategory.FRESH, defaultUnit: Unit.PIECE },
    { name: 'clémentine', category: IngredientCategory.FRESH, defaultUnit: Unit.PIECE },
    { name: 'mandarine', category: IngredientCategory.FRESH, defaultUnit: Unit.PIECE },
    { name: 'pamplemousse', category: IngredientCategory.FRESH, defaultUnit: Unit.PIECE },
    { name: 'raisin', category: IngredientCategory.FRESH, defaultUnit: Unit.G },
    { name: 'fraise', category: IngredientCategory.FRESH, defaultUnit: Unit.G },
    { name: 'framboise', category: IngredientCategory.FRESH, defaultUnit: Unit.G },
    { name: 'mûre', category: IngredientCategory.FRESH, defaultUnit: Unit.G },
    { name: 'myrtille', category: IngredientCategory.FRESH, defaultUnit: Unit.G },
    { name: 'cassis', category: IngredientCategory.FRESH, defaultUnit: Unit.G },
    { name: 'groseille', category: IngredientCategory.FRESH, defaultUnit: Unit.G },
    { name: 'cerise', category: IngredientCategory.FRESH, defaultUnit: Unit.G },
    { name: 'pêche', category: IngredientCategory.FRESH, defaultUnit: Unit.PIECE },
    { name: 'nectarine', category: IngredientCategory.FRESH, defaultUnit: Unit.PIECE },
    { name: 'abricot', category: IngredientCategory.FRESH, defaultUnit: Unit.PIECE },
    { name: 'prune', category: IngredientCategory.FRESH, defaultUnit: Unit.PIECE },
    { name: 'mirabelle', category: IngredientCategory.FRESH, defaultUnit: Unit.G },
    { name: 'quetsche', category: IngredientCategory.FRESH, defaultUnit: Unit.G },
    { name: 'mangue', category: IngredientCategory.FRESH, defaultUnit: Unit.PIECE },
    { name: 'ananas', category: IngredientCategory.FRESH, defaultUnit: Unit.PIECE },
    { name: 'papaye', category: IngredientCategory.FRESH, defaultUnit: Unit.PIECE },
    { name: 'kiwi', category: IngredientCategory.FRESH, defaultUnit: Unit.PIECE },
    { name: 'passion', category: IngredientCategory.FRESH, defaultUnit: Unit.PIECE },
    { name: 'grenade', category: IngredientCategory.FRESH, defaultUnit: Unit.PIECE },
    { name: 'figue', category: IngredientCategory.FRESH, defaultUnit: Unit.PIECE },
    { name: 'datte', category: IngredientCategory.FRESH, defaultUnit: Unit.PIECE },
    { name: 'rhubarbe', category: IngredientCategory.FRESH, defaultUnit: Unit.G },
    { name: 'coing', category: IngredientCategory.FRESH, defaultUnit: Unit.PIECE },
    { name: 'nèfle', category: IngredientCategory.FRESH, defaultUnit: Unit.PIECE },

    // === HERBES AROMATIQUES SUPPLÉMENTAIRES ===
    { name: 'ciboulette', category: IngredientCategory.SPICES, defaultUnit: Unit.BUNCH },
    { name: 'estragon', category: IngredientCategory.SPICES, defaultUnit: Unit.BUNCH },
    { name: 'cerfeuil', category: IngredientCategory.SPICES, defaultUnit: Unit.BUNCH },
    { name: 'menthe', category: IngredientCategory.SPICES, defaultUnit: Unit.BUNCH },
    { name: 'mélisse', category: IngredientCategory.SPICES, defaultUnit: Unit.BUNCH },
    { name: 'verveine', category: IngredientCategory.SPICES, defaultUnit: Unit.BUNCH },
    { name: 'romarin', category: IngredientCategory.SPICES, defaultUnit: Unit.BUNCH },
    { name: 'sauge', category: IngredientCategory.SPICES, defaultUnit: Unit.BUNCH },
    { name: 'origan', category: IngredientCategory.SPICES, defaultUnit: Unit.BUNCH },
    { name: 'marjolaine', category: IngredientCategory.SPICES, defaultUnit: Unit.BUNCH },
    { name: 'sarriette', category: IngredientCategory.SPICES, defaultUnit: Unit.BUNCH },
    { name: 'livèche', category: IngredientCategory.SPICES, defaultUnit: Unit.BUNCH },
    { name: 'raifort', category: IngredientCategory.SPICES, defaultUnit: Unit.G },
    { name: 'gingembre frais', category: IngredientCategory.SPICES, defaultUnit: Unit.G },
    { name: 'galanga', category: IngredientCategory.SPICES, defaultUnit: Unit.G },
    { name: 'citronnelle', category: IngredientCategory.SPICES, defaultUnit: Unit.PIECE },
    { name: 'curcuma frais', category: IngredientCategory.SPICES, defaultUnit: Unit.G },
    { name: 'fenugrec', category: IngredientCategory.SPICES, defaultUnit: Unit.TSP },
    { name: 'graines de coriandre', category: IngredientCategory.SPICES, defaultUnit: Unit.TSP },
    { name: 'graines de fenouil', category: IngredientCategory.SPICES, defaultUnit: Unit.TSP },

    // === VIANDES SUPPLÉMENTAIRES ===
    { name: 'boeuf', category: IngredientCategory.MEAT, defaultUnit: Unit.G },
    { name: 'steak', category: IngredientCategory.MEAT, defaultUnit: Unit.PIECE },
    { name: 'rôti de boeuf', category: IngredientCategory.MEAT, defaultUnit: Unit.G },
    { name: 'boeuf bourguignon', category: IngredientCategory.MEAT, defaultUnit: Unit.G },
    { name: 'bavette', category: IngredientCategory.MEAT, defaultUnit: Unit.G },
    { name: 'onglet', category: IngredientCategory.MEAT, defaultUnit: Unit.G },
    { name: 'filet de boeuf', category: IngredientCategory.MEAT, defaultUnit: Unit.G },
    { name: 'entrecôte', category: IngredientCategory.MEAT, defaultUnit: Unit.PIECE },
    { name: 'côte de boeuf', category: IngredientCategory.MEAT, defaultUnit: Unit.PIECE },
    { name: 'jarret de boeuf', category: IngredientCategory.MEAT, defaultUnit: Unit.G },
    { name: 'palette de porc', category: IngredientCategory.MEAT, defaultUnit: Unit.G },
    { name: 'échine de porc', category: IngredientCategory.MEAT, defaultUnit: Unit.G },
    { name: 'côtes de porc', category: IngredientCategory.MEAT, defaultUnit: Unit.PIECE },
    { name: 'rôti de porc', category: IngredientCategory.MEAT, defaultUnit: Unit.G },
    { name: 'filet de porc', category: IngredientCategory.MEAT, defaultUnit: Unit.G },
    { name: 'cuisse de poulet', category: IngredientCategory.MEAT, defaultUnit: Unit.PIECE },
    { name: 'aile de poulet', category: IngredientCategory.MEAT, defaultUnit: Unit.PIECE },
    { name: 'blanc de poulet', category: IngredientCategory.MEAT, defaultUnit: Unit.PIECE },
    { name: 'poulet entier', category: IngredientCategory.MEAT, defaultUnit: Unit.PIECE },
    { name: 'pigeon', category: IngredientCategory.MEAT, defaultUnit: Unit.PIECE },
    { name: 'lapin', category: IngredientCategory.MEAT, defaultUnit: Unit.PIECE },
    { name: 'gigot d\'agneau', category: IngredientCategory.MEAT, defaultUnit: Unit.G },
    { name: 'épaule d\'agneau', category: IngredientCategory.MEAT, defaultUnit: Unit.G },
    { name: 'côtelettes d\'agneau', category: IngredientCategory.MEAT, defaultUnit: Unit.PIECE },
    { name: 'agneau haché', category: IngredientCategory.MEAT, defaultUnit: Unit.G },
    { name: 'canard', category: IngredientCategory.MEAT, defaultUnit: Unit.PIECE },
    { name: 'magret de canard', category: IngredientCategory.MEAT, defaultUnit: Unit.PIECE },
    { name: 'cuisse de canard', category: IngredientCategory.MEAT, defaultUnit: Unit.PIECE },
    { name: 'oie', category: IngredientCategory.MEAT, defaultUnit: Unit.PIECE },
    { name: 'dinde', category: IngredientCategory.MEAT, defaultUnit: Unit.PIECE },
    { name: 'foie de volaille', category: IngredientCategory.MEAT, defaultUnit: Unit.G },
    { name: 'gésier', category: IngredientCategory.MEAT, defaultUnit: Unit.G },
    { name: 'rognon', category: IngredientCategory.MEAT, defaultUnit: Unit.G },
    { name: 'cervelle', category: IngredientCategory.MEAT, defaultUnit: Unit.G },
    { name: 'ris de veau', category: IngredientCategory.MEAT, defaultUnit: Unit.G },
    { name: 'tripes', category: IngredientCategory.MEAT, defaultUnit: Unit.G },
    { name: 'boudin noir', category: IngredientCategory.MEAT, defaultUnit: Unit.PIECE },
    { name: 'boudin blanc', category: IngredientCategory.MEAT, defaultUnit: Unit.PIECE },
    { name: 'andouille', category: IngredientCategory.MEAT, defaultUnit: Unit.PIECE },
    { name: 'andouillette', category: IngredientCategory.MEAT, defaultUnit: Unit.PIECE },
    { name: 'chorizo', category: IngredientCategory.MEAT, defaultUnit: Unit.PIECE },
    { name: 'saucisson', category: IngredientCategory.MEAT, defaultUnit: Unit.PIECE },
    { name: 'jambon cru', category: IngredientCategory.MEAT, defaultUnit: Unit.SLICE },
    { name: 'prosciutto', category: IngredientCategory.MEAT, defaultUnit: Unit.SLICE },
    { name: 'coppa', category: IngredientCategory.MEAT, defaultUnit: Unit.SLICE },
    { name: 'jambon de Parme', category: IngredientCategory.MEAT, defaultUnit: Unit.SLICE },
    { name: 'jambon de Bayonne', category: IngredientCategory.MEAT, defaultUnit: Unit.SLICE },
    { name: 'viande des Grisons', category: IngredientCategory.MEAT, defaultUnit: Unit.SLICE },
    { name: 'bacon', category: IngredientCategory.MEAT, defaultUnit: Unit.SLICE },

    // === POISSONS ET FRUITS DE MER SUPPLÉMENTAIRES ===
    { name: 'bar', category: IngredientCategory.FISH, defaultUnit: Unit.G },
    { name: 'daurade', category: IngredientCategory.FISH, defaultUnit: Unit.G },
    { name: 'dorade', category: IngredientCategory.FISH, defaultUnit: Unit.G },
    { name: 'loup de mer', category: IngredientCategory.FISH, defaultUnit: Unit.G },
    { name: 'maquereau', category: IngredientCategory.FISH, defaultUnit: Unit.G },
    { name: 'hareng', category: IngredientCategory.FISH, defaultUnit: Unit.G },
    { name: 'sardine', category: IngredientCategory.FISH, defaultUnit: Unit.G },
    { name: 'anchois', category: IngredientCategory.FISH, defaultUnit: Unit.G },
    { name: 'thon blanc', category: IngredientCategory.FISH, defaultUnit: Unit.G },
    { name: 'espadon', category: IngredientCategory.FISH, defaultUnit: Unit.G },
    { name: 'escolier', category: IngredientCategory.FISH, defaultUnit: Unit.G },
    { name: 'rouget', category: IngredientCategory.FISH, defaultUnit: Unit.G },
    { name: 'lotte', category: IngredientCategory.FISH, defaultUnit: Unit.G },
    { name: 'raie', category: IngredientCategory.FISH, defaultUnit: Unit.G },
    { name: 'rascasse', category: IngredientCategory.FISH, defaultUnit: Unit.G },
    { name: 'turbot', category: IngredientCategory.FISH, defaultUnit: Unit.G },
    { name: 'saint-pierre', category: IngredientCategory.FISH, defaultUnit: Unit.G },
    { name: 'sole', category: IngredientCategory.FISH, defaultUnit: Unit.G },
    { name: 'plie', category: IngredientCategory.FISH, defaultUnit: Unit.G },
    { name: 'limande', category: IngredientCategory.FISH, defaultUnit: Unit.G },
    { name: 'flet', category: IngredientCategory.FISH, defaultUnit: Unit.G },
    { name: 'flétan', category: IngredientCategory.FISH, defaultUnit: Unit.G },
    { name: 'églefin', category: IngredientCategory.FISH, defaultUnit: Unit.G },
    { name: 'colin', category: IngredientCategory.FISH, defaultUnit: Unit.G },
    { name: 'merlu', category: IngredientCategory.FISH, defaultUnit: Unit.G },
    { name: 'lieu', category: IngredientCategory.FISH, defaultUnit: Unit.G },
    { name: 'brochet', category: IngredientCategory.FISH, defaultUnit: Unit.G },
    { name: 'perche', category: IngredientCategory.FISH, defaultUnit: Unit.G },
    { name: 'sandre', category: IngredientCategory.FISH, defaultUnit: Unit.G },
    { name: 'truite', category: IngredientCategory.FISH, defaultUnit: Unit.G },
    { name: 'anguille', category: IngredientCategory.FISH, defaultUnit: Unit.G },
    { name: 'carpe', category: IngredientCategory.FISH, defaultUnit: Unit.G },
    { name: 'saumon fumé', category: IngredientCategory.FISH, defaultUnit: Unit.G },
    { name: 'truite fumée', category: IngredientCategory.FISH, defaultUnit: Unit.G },
    { name: 'thon en conserve', category: IngredientCategory.FISH, defaultUnit: Unit.G },
    { name: 'sardine en conserve', category: IngredientCategory.FISH, defaultUnit: Unit.G },
    { name: 'anchois en conserve', category: IngredientCategory.FISH, defaultUnit: Unit.G },
    { name: 'huître', category: IngredientCategory.FISH, defaultUnit: Unit.PIECE },
    { name: 'moule', category: IngredientCategory.FISH, defaultUnit: Unit.G },
    { name: 'palourde', category: IngredientCategory.FISH, defaultUnit: Unit.G },
    { name: 'coque', category: IngredientCategory.FISH, defaultUnit: Unit.G },
    { name: 'praire', category: IngredientCategory.FISH, defaultUnit: Unit.G },
    { name: 'amande', category: IngredientCategory.FISH, defaultUnit: Unit.PIECE },
    { name: 'pétoncle', category: IngredientCategory.FISH, defaultUnit: Unit.PIECE },
    { name: 'coquille Saint-Jacques', category: IngredientCategory.FISH, defaultUnit: Unit.PIECE },
    { name: 'calamar', category: IngredientCategory.FISH, defaultUnit: Unit.G },
    { name: 'calamar', category: IngredientCategory.FISH, defaultUnit: Unit.G },
    { name: 'encornet', category: IngredientCategory.FISH, defaultUnit: Unit.G },
    { name: 'poulpe', category: IngredientCategory.FISH, defaultUnit: Unit.G },
    { name: 'seiche', category: IngredientCategory.FISH, defaultUnit: Unit.G },
    { name: 'crevette rose', category: IngredientCategory.FISH, defaultUnit: Unit.G },
    { name: 'crevette grise', category: IngredientCategory.FISH, defaultUnit: Unit.G },
    { name: 'crevette tigrée', category: IngredientCategory.FISH, defaultUnit: Unit.G },
    { name: 'gambas', category: IngredientCategory.FISH, defaultUnit: Unit.PIECE },
    { name: 'langoustine', category: IngredientCategory.FISH, defaultUnit: Unit.PIECE },
    { name: 'langouste', category: IngredientCategory.FISH, defaultUnit: Unit.PIECE },
    { name: 'homard', category: IngredientCategory.FISH, defaultUnit: Unit.PIECE },
    { name: 'tourteau', category: IngredientCategory.FISH, defaultUnit: Unit.PIECE },
    { name: 'araignée de mer', category: IngredientCategory.FISH, defaultUnit: Unit.PIECE },
    { name: 'crabe', category: IngredientCategory.FISH, defaultUnit: Unit.PIECE },
    { name: 'bigorneau', category: IngredientCategory.FISH, defaultUnit: Unit.G },
    { name: 'bulot', category: IngredientCategory.FISH, defaultUnit: Unit.PIECE },

    // === PRODUITS LAITIERS SUPPLÉMENTAIRES ===
    { name: 'crème liquide', category: IngredientCategory.DAIRY, defaultUnit: Unit.ML },
    { name: 'crème épaisse', category: IngredientCategory.DAIRY, defaultUnit: Unit.ML },
    { name: 'crème chantilly', category: IngredientCategory.DAIRY, defaultUnit: Unit.ML },
    { name: 'lait de coco', category: IngredientCategory.DAIRY, defaultUnit: Unit.ML },
    { name: 'lait d\'amande', category: IngredientCategory.DAIRY, defaultUnit: Unit.ML },
    { name: 'lait de soja', category: IngredientCategory.DAIRY, defaultUnit: Unit.ML },
    { name: 'lait de riz', category: IngredientCategory.DAIRY, defaultUnit: Unit.ML },
    { name: 'lait de chèvre', category: IngredientCategory.DAIRY, defaultUnit: Unit.ML },
    { name: 'yaourt grec', category: IngredientCategory.DAIRY, defaultUnit: Unit.G },
    { name: 'yaourt nature', category: IngredientCategory.DAIRY, defaultUnit: Unit.G },
    { name: 'fromage blanc', category: IngredientCategory.DAIRY, defaultUnit: Unit.G },
    { name: 'faisselle', category: IngredientCategory.DAIRY, defaultUnit: Unit.G },
    { name: 'petit-suisse', category: IngredientCategory.DAIRY, defaultUnit: Unit.PIECE },
    { name: 'ricotta', category: IngredientCategory.DAIRY, defaultUnit: Unit.G },
    { name: 'mascarpone', category: IngredientCategory.DAIRY, defaultUnit: Unit.G },
    { name: 'bûche de chèvre', category: IngredientCategory.DAIRY, defaultUnit: Unit.G },
    { name: 'chèvre frais', category: IngredientCategory.DAIRY, defaultUnit: Unit.G },
    { name: 'fromage de chèvre sec', category: IngredientCategory.DAIRY, defaultUnit: Unit.G },
    { name: 'roquefort', category: IngredientCategory.DAIRY, defaultUnit: Unit.G },
    { name: 'bleu', category: IngredientCategory.DAIRY, defaultUnit: Unit.G },
    { name: 'fourme d\'Ambert', category: IngredientCategory.DAIRY, defaultUnit: Unit.G },
    { name: 'stilton', category: IngredientCategory.DAIRY, defaultUnit: Unit.G },
    { name: 'gorgonzola', category: IngredientCategory.DAIRY, defaultUnit: Unit.G },
    { name: 'camembert', category: IngredientCategory.DAIRY, defaultUnit: Unit.PIECE },
    { name: 'brie', category: IngredientCategory.DAIRY, defaultUnit: Unit.PIECE },
    { name: 'coulommiers', category: IngredientCategory.DAIRY, defaultUnit: Unit.PIECE },
    { name: 'reblochon', category: IngredientCategory.DAIRY, defaultUnit: Unit.PIECE },
    { name: 'tome', category: IngredientCategory.DAIRY, defaultUnit: Unit.G },
    { name: 'cantal', category: IngredientCategory.DAIRY, defaultUnit: Unit.G },
    { name: 'salers', category: IngredientCategory.DAIRY, defaultUnit: Unit.G },
    { name: 'comté', category: IngredientCategory.DAIRY, defaultUnit: Unit.G },
    { name: 'beaufort', category: IngredientCategory.DAIRY, defaultUnit: Unit.G },
    { name: 'gruyère', category: IngredientCategory.DAIRY, defaultUnit: Unit.G },
    { name: 'emmental', category: IngredientCategory.DAIRY, defaultUnit: Unit.G },
    { name: 'gouda', category: IngredientCategory.DAIRY, defaultUnit: Unit.G },
    { name: 'cheddar', category: IngredientCategory.DAIRY, defaultUnit: Unit.G },
    { name: 'chèvre râpé', category: IngredientCategory.DAIRY, defaultUnit: Unit.G },
    { name: 'parmesan râpé', category: IngredientCategory.DAIRY, defaultUnit: Unit.G },
    { name: 'pecorino', category: IngredientCategory.DAIRY, defaultUnit: Unit.G },
    { name: 'feta', category: IngredientCategory.DAIRY, defaultUnit: Unit.G },
    { name: 'halloumi', category: IngredientCategory.DAIRY, defaultUnit: Unit.G },
    { name: 'burrata', category: IngredientCategory.DAIRY, defaultUnit: Unit.PIECE },
    { name: 'ricotta salata', category: IngredientCategory.DAIRY, defaultUnit: Unit.G },
    { name: 'fromage frais', category: IngredientCategory.DAIRY, defaultUnit: Unit.G },
    { name: 'petit-lait', category: IngredientCategory.DAIRY, defaultUnit: Unit.ML },
    { name: 'lait ribot', category: IngredientCategory.DAIRY, defaultUnit: Unit.ML },
    { name: 'kéfir', category: IngredientCategory.DAIRY, defaultUnit: Unit.ML },
    { name: 'lait fermenté', category: IngredientCategory.DAIRY, defaultUnit: Unit.ML },

    // === CÉRÉALES ET FARINES SUPPLÉMENTAIRES ===
    { name: 'flocons d\'avoine', category: IngredientCategory.PANTRY, defaultUnit: Unit.G },
    { name: 'flocons d\'orge', category: IngredientCategory.PANTRY, defaultUnit: Unit.G },
    { name: 'flocons de blé', category: IngredientCategory.PANTRY, defaultUnit: Unit.G },
    { name: 'orge', category: IngredientCategory.PANTRY, defaultUnit: Unit.G },
    { name: 'blé', category: IngredientCategory.PANTRY, defaultUnit: Unit.G },
    { name: 'épeautre', category: IngredientCategory.PANTRY, defaultUnit: Unit.G },
    { name: 'seigle', category: IngredientCategory.PANTRY, defaultUnit: Unit.G },
    { name: 'sarrasin', category: IngredientCategory.PANTRY, defaultUnit: Unit.G },
    { name: 'millet', category: IngredientCategory.PANTRY, defaultUnit: Unit.G },
    { name: 'amarante', category: IngredientCategory.PANTRY, defaultUnit: Unit.G },
    { name: 'boulgour', category: IngredientCategory.PANTRY, defaultUnit: Unit.G },
    { name: 'couscous', category: IngredientCategory.PANTRY, defaultUnit: Unit.G },
    { name: 'semoule', category: IngredientCategory.PANTRY, defaultUnit: Unit.G },
    { name: 'polenta', category: IngredientCategory.PANTRY, defaultUnit: Unit.G },
    { name: 'farine de blé', category: IngredientCategory.PANTRY, defaultUnit: Unit.G },
    { name: 'farine de blé complète', category: IngredientCategory.PANTRY, defaultUnit: Unit.G },
    { name: 'farine de seigle', category: IngredientCategory.PANTRY, defaultUnit: Unit.G },
    { name: 'farine de sarrasin', category: IngredientCategory.PANTRY, defaultUnit: Unit.G },
    { name: 'farine de maïs', category: IngredientCategory.PANTRY, defaultUnit: Unit.G },
    { name: 'farine de châtaigne', category: IngredientCategory.PANTRY, defaultUnit: Unit.G },
    { name: 'farine de riz', category: IngredientCategory.PANTRY, defaultUnit: Unit.G },
    { name: 'farine de pois chiches', category: IngredientCategory.PANTRY, defaultUnit: Unit.G },
    { name: 'maïzena', category: IngredientCategory.PANTRY, defaultUnit: Unit.G },
    { name: 'fécule de pomme de terre', category: IngredientCategory.PANTRY, defaultUnit: Unit.G },
    { name: 'levure de boulanger', category: IngredientCategory.PANTRY, defaultUnit: Unit.G },
    { name: 'levure chimique', category: IngredientCategory.PANTRY, defaultUnit: Unit.G },
    { name: 'bicarbonate de soude', category: IngredientCategory.PANTRY, defaultUnit: Unit.TSP },
    { name: 'levure sèche', category: IngredientCategory.PANTRY, defaultUnit: Unit.G },
    { name: 'nouilles de riz', category: IngredientCategory.PANTRY, defaultUnit: Unit.G },
    { name: 'nouilles soba', category: IngredientCategory.PANTRY, defaultUnit: Unit.G },
    { name: 'nouilles udon', category: IngredientCategory.PANTRY, defaultUnit: Unit.G },
    { name: 'vermicelle de riz', category: IngredientCategory.PANTRY, defaultUnit: Unit.G },
    { name: 'pâtes fraîches', category: IngredientCategory.PANTRY, defaultUnit: Unit.G },
    { name: 'gnocchi', category: IngredientCategory.PANTRY, defaultUnit: Unit.G },
    { name: 'ravioli', category: IngredientCategory.PANTRY, defaultUnit: Unit.G },
    { name: 'tortellini', category: IngredientCategory.PANTRY, defaultUnit: Unit.G },
    { name: 'cannelloni', category: IngredientCategory.PANTRY, defaultUnit: Unit.PIECE },
    { name: 'lasagnes', category: IngredientCategory.PANTRY, defaultUnit: Unit.PIECE },
    { name: 'tortilla', category: IngredientCategory.PANTRY, defaultUnit: Unit.PIECE },
    { name: 'galette de sarrasin', category: IngredientCategory.PANTRY, defaultUnit: Unit.PIECE },
    { name: 'pâte brisée', category: IngredientCategory.FROZEN, defaultUnit: Unit.PIECE },
    { name: 'pâte sablée', category: IngredientCategory.FROZEN, defaultUnit: Unit.PIECE },
    { name: 'pâte à pizza', category: IngredientCategory.FROZEN, defaultUnit: Unit.PIECE },

    // === LÉGUMINEUSES SUPPLÉMENTAIRES ===
    { name: 'lentilles vertes', category: IngredientCategory.PANTRY, defaultUnit: Unit.G },
    { name: 'lentilles corail', category: IngredientCategory.PANTRY, defaultUnit: Unit.G },
    { name: 'lentilles beluga', category: IngredientCategory.PANTRY, defaultUnit: Unit.G },
    { name: 'haricots blancs', category: IngredientCategory.PANTRY, defaultUnit: Unit.G },
    { name: 'haricots noirs', category: IngredientCategory.PANTRY, defaultUnit: Unit.G },
    { name: 'haricots azuki', category: IngredientCategory.PANTRY, defaultUnit: Unit.G },
    { name: 'flageolets', category: IngredientCategory.PANTRY, defaultUnit: Unit.G },
    { name: 'cocos de Paimpol', category: IngredientCategory.PANTRY, defaultUnit: Unit.G },
    { name: 'tarbais', category: IngredientCategory.PANTRY, defaultUnit: Unit.G },
    { name: 'mung beans', category: IngredientCategory.PANTRY, defaultUnit: Unit.G },
    { name: 'haricots mungo', category: IngredientCategory.PANTRY, defaultUnit: Unit.G },
    { name: 'fèves', category: IngredientCategory.PANTRY, defaultUnit: Unit.G },
    { name: 'edamame', category: IngredientCategory.PANTRY, defaultUnit: Unit.G },
    { name: 'soja', category: IngredientCategory.PANTRY, defaultUnit: Unit.G },
    { name: 'tofu', category: IngredientCategory.PANTRY, defaultUnit: Unit.G },
    { name: 'tofu ferme', category: IngredientCategory.PANTRY, defaultUnit: Unit.G },
    { name: 'tofu soyeux', category: IngredientCategory.PANTRY, defaultUnit: Unit.G },
    { name: 'tempeh', category: IngredientCategory.PANTRY, defaultUnit: Unit.G },

    // === NOIX ET GRAINES ===
    { name: 'amande', category: IngredientCategory.PANTRY, defaultUnit: Unit.G },
    { name: 'noix', category: IngredientCategory.PANTRY, defaultUnit: Unit.G },
    { name: 'noisette', category: IngredientCategory.PANTRY, defaultUnit: Unit.G },
    { name: 'noix de cajou', category: IngredientCategory.PANTRY, defaultUnit: Unit.G },
    { name: 'noix de pécan', category: IngredientCategory.PANTRY, defaultUnit: Unit.G },
    { name: 'noix de macadamia', category: IngredientCategory.PANTRY, defaultUnit: Unit.G },
    { name: 'pistache', category: IngredientCategory.PANTRY, defaultUnit: Unit.G },
    { name: 'pignon de pin', category: IngredientCategory.PANTRY, defaultUnit: Unit.G },
    { name: 'cacahuète', category: IngredientCategory.PANTRY, defaultUnit: Unit.G },
    { name: 'graine de tournesol', category: IngredientCategory.PANTRY, defaultUnit: Unit.G },
    { name: 'graine de courge', category: IngredientCategory.PANTRY, defaultUnit: Unit.G },
    { name: 'graine de sésame', category: IngredientCategory.PANTRY, defaultUnit: Unit.G },
    { name: 'graine de chia', category: IngredientCategory.PANTRY, defaultUnit: Unit.G },
    { name: 'graine de lin', category: IngredientCategory.PANTRY, defaultUnit: Unit.G },
    { name: 'graine de pavot', category: IngredientCategory.PANTRY, defaultUnit: Unit.G },
    { name: 'noix de coco râpée', category: IngredientCategory.PANTRY, defaultUnit: Unit.G },
    { name: 'marron', category: IngredientCategory.PANTRY, defaultUnit: Unit.G },
    { name: 'châtaigne', category: IngredientCategory.PANTRY, defaultUnit: Unit.G },

    // === ÉPICES SUPPLÉMENTAIRES ===
    { name: 'cannelle', category: IngredientCategory.SPICES, defaultUnit: Unit.TSP },
    { name: 'muscade', category: IngredientCategory.SPICES, defaultUnit: Unit.TSP },
    { name: 'clou de girofle', category: IngredientCategory.SPICES, defaultUnit: Unit.PIECE },
    { name: 'anis étoilé', category: IngredientCategory.SPICES, defaultUnit: Unit.PIECE },
    { name: 'cardamome', category: IngredientCategory.SPICES, defaultUnit: Unit.TSP },
    { name: 'coriandre en poudre', category: IngredientCategory.SPICES, defaultUnit: Unit.TSP },
    { name: 'fenugrec en poudre', category: IngredientCategory.SPICES, defaultUnit: Unit.TSP },
    { name: 'gingembre en poudre', category: IngredientCategory.SPICES, defaultUnit: Unit.TSP },
    { name: 'curcuma en poudre', category: IngredientCategory.SPICES, defaultUnit: Unit.TSP },
    { name: 'garam masala', category: IngredientCategory.SPICES, defaultUnit: Unit.TSP },
    { name: 'ras el hanout', category: IngredientCategory.SPICES, defaultUnit: Unit.TSP },
    { name: 'curry rouge', category: IngredientCategory.SPICES, defaultUnit: Unit.TSP },
    { name: 'curry vert', category: IngredientCategory.SPICES, defaultUnit: Unit.TSP },
    { name: 'piment de Cayenne', category: IngredientCategory.SPICES, defaultUnit: Unit.TSP },
    { name: 'piment d\'Espelette', category: IngredientCategory.SPICES, defaultUnit: Unit.TSP },
    { name: 'piment', category: IngredientCategory.SPICES, defaultUnit: Unit.PIECE },
    { name: 'piment fort', category: IngredientCategory.SPICES, defaultUnit: Unit.PIECE },
    { name: 'piment doux', category: IngredientCategory.SPICES, defaultUnit: Unit.PIECE },
    { name: 'piment oiseau', category: IngredientCategory.SPICES, defaultUnit: Unit.PIECE },
    { name: 'piment chipotle', category: IngredientCategory.SPICES, defaultUnit: Unit.TSP },
    { name: 'pâte de piment', category: IngredientCategory.SPICES, defaultUnit: Unit.TSP },
    { name: 'sauce sriracha', category: IngredientCategory.SPICES, defaultUnit: Unit.TSP },
    { name: 'sambal oelek', category: IngredientCategory.SPICES, defaultUnit: Unit.TSP },
    { name: 'harissa', category: IngredientCategory.SPICES, defaultUnit: Unit.TSP },
    { name: 'paprika doux', category: IngredientCategory.SPICES, defaultUnit: Unit.TSP },
    { name: 'paprika fumé', category: IngredientCategory.SPICES, defaultUnit: Unit.TSP },
    { name: 'fumée liquide', category: IngredientCategory.SPICES, defaultUnit: Unit.TSP },
    { name: 'safran', category: IngredientCategory.SPICES, defaultUnit: Unit.PINCH },
    { name: 'sumac', category: IngredientCategory.SPICES, defaultUnit: Unit.TSP },
    { name: 'za\'atar', category: IngredientCategory.SPICES, defaultUnit: Unit.TSP },
    { name: 'baharat', category: IngredientCategory.SPICES, defaultUnit: Unit.TSP },
    { name: 'berbère', category: IngredientCategory.SPICES, defaultUnit: Unit.TSP },

    // === HUILES ET VINAIGRES ===
    { name: 'huile de tournesol', category: IngredientCategory.PANTRY, defaultUnit: Unit.TBSP },
    { name: 'huile de colza', category: IngredientCategory.PANTRY, defaultUnit: Unit.TBSP },
    { name: 'huile de sésame', category: IngredientCategory.PANTRY, defaultUnit: Unit.TBSP },
    { name: 'huile de coco', category: IngredientCategory.PANTRY, defaultUnit: Unit.TBSP },
    { name: 'huile de pépins de raisin', category: IngredientCategory.PANTRY, defaultUnit: Unit.TBSP },
    { name: 'huile d\'arachide', category: IngredientCategory.PANTRY, defaultUnit: Unit.TBSP },
    { name: 'huile de noisette', category: IngredientCategory.PANTRY, defaultUnit: Unit.TBSP },
    { name: 'huile de noix', category: IngredientCategory.PANTRY, defaultUnit: Unit.TBSP },
    { name: 'vinaigre de vin rouge', category: IngredientCategory.PANTRY, defaultUnit: Unit.TBSP },
    { name: 'vinaigre de vin blanc', category: IngredientCategory.PANTRY, defaultUnit: Unit.TBSP },
    { name: 'vinaigre de cidre', category: IngredientCategory.PANTRY, defaultUnit: Unit.TBSP },
    { name: 'vinaigre balsamique', category: IngredientCategory.PANTRY, defaultUnit: Unit.TBSP },
    { name: 'vinaigre de Xérès', category: IngredientCategory.PANTRY, defaultUnit: Unit.TBSP },
    { name: 'vinaigre de riz', category: IngredientCategory.PANTRY, defaultUnit: Unit.TBSP },
    { name: 'vinaigre de framboise', category: IngredientCategory.PANTRY, defaultUnit: Unit.TBSP },
    { name: 'jus de citron vert', category: IngredientCategory.FRESH, defaultUnit: Unit.TBSP },
    { name: 'citron vert', category: IngredientCategory.FRESH, defaultUnit: Unit.PIECE },
    { name: 'yuzu', category: IngredientCategory.FRESH, defaultUnit: Unit.PIECE },

    // === SUCRE ET ÉDULCORANTS ===
    { name: 'sucre blanc', category: IngredientCategory.PANTRY, defaultUnit: Unit.G },
    { name: 'sucre roux', category: IngredientCategory.PANTRY, defaultUnit: Unit.G },
    { name: 'cassonade', category: IngredientCategory.PANTRY, defaultUnit: Unit.G },
    { name: 'sucre complet', category: IngredientCategory.PANTRY, defaultUnit: Unit.G },
    { name: 'sucre de canne', category: IngredientCategory.PANTRY, defaultUnit: Unit.G },
    { name: 'miel', category: IngredientCategory.PANTRY, defaultUnit: Unit.TBSP },
    { name: 'sirop d\'érable', category: IngredientCategory.PANTRY, defaultUnit: Unit.TBSP },
    { name: 'sirop d\'agave', category: IngredientCategory.PANTRY, defaultUnit: Unit.TBSP },
    { name: 'sirop de riz', category: IngredientCategory.PANTRY, defaultUnit: Unit.TBSP },
    { name: 'mélasse', category: IngredientCategory.PANTRY, defaultUnit: Unit.TBSP },
    { name: 'stevia', category: IngredientCategory.PANTRY, defaultUnit: Unit.TSP },
    { name: 'fructose', category: IngredientCategory.PANTRY, defaultUnit: Unit.G },
    { name: 'sucre glace', category: IngredientCategory.PANTRY, defaultUnit: Unit.G },
    { name: 'vermicelle', category: IngredientCategory.PANTRY, defaultUnit: Unit.G },

    // === BOISSONS ===
    { name: 'vin rouge', category: IngredientCategory.BEVERAGES, defaultUnit: Unit.ML },
    { name: 'vin blanc', category: IngredientCategory.BEVERAGES, defaultUnit: Unit.ML },
    { name: 'vin rosé', category: IngredientCategory.BEVERAGES, defaultUnit: Unit.ML },
    { name: 'champagne', category: IngredientCategory.BEVERAGES, defaultUnit: Unit.ML },
    { name: 'vin de porto', category: IngredientCategory.BEVERAGES, defaultUnit: Unit.ML },
    { name: 'sherry', category: IngredientCategory.BEVERAGES, defaultUnit: Unit.ML },
    { name: 'cognac', category: IngredientCategory.BEVERAGES, defaultUnit: Unit.ML },
    { name: 'armagnac', category: IngredientCategory.BEVERAGES, defaultUnit: Unit.ML },
    { name: 'calvados', category: IngredientCategory.BEVERAGES, defaultUnit: Unit.ML },
    { name: 'rhum', category: IngredientCategory.BEVERAGES, defaultUnit: Unit.ML },
    { name: 'whisky', category: IngredientCategory.BEVERAGES, defaultUnit: Unit.ML },
    { name: 'sake', category: IngredientCategory.BEVERAGES, defaultUnit: Unit.ML },
    { name: 'mirin', category: IngredientCategory.BEVERAGES, defaultUnit: Unit.ML },
    { name: 'vinaigre de riz pour sushi', category: IngredientCategory.PANTRY, defaultUnit: Unit.TBSP },
    { name: 'bière', category: IngredientCategory.BEVERAGES, defaultUnit: Unit.ML },
    { name: 'cidre', category: IngredientCategory.BEVERAGES, defaultUnit: Unit.ML },

    // === CONSERVES ET PRÉPARATIONS ===
    { name: 'tomate séchée', category: IngredientCategory.PANTRY, defaultUnit: Unit.G },
    { name: 'olive noire', category: IngredientCategory.PANTRY, defaultUnit: Unit.G },
    { name: 'olive verte', category: IngredientCategory.PANTRY, defaultUnit: Unit.G },
    { name: 'câpre', category: IngredientCategory.PANTRY, defaultUnit: Unit.G },
    { name: 'cornichon', category: IngredientCategory.PANTRY, defaultUnit: Unit.G },
    { name: 'citron confit', category: IngredientCategory.PANTRY, defaultUnit: Unit.PIECE },
    { name: 'confiture', category: IngredientCategory.PANTRY, defaultUnit: Unit.TBSP },
    { name: 'marmelade', category: IngredientCategory.PANTRY, defaultUnit: Unit.TBSP },
    { name: 'pâte d\'amande', category: IngredientCategory.PANTRY, defaultUnit: Unit.G },
    { name: 'praliné', category: IngredientCategory.PANTRY, defaultUnit: Unit.G },
    { name: 'pâte de sésame', category: IngredientCategory.PANTRY, defaultUnit: Unit.TBSP },
    { name: 'tahini', category: IngredientCategory.PANTRY, defaultUnit: Unit.TBSP },
    { name: 'houmous', category: IngredientCategory.PANTRY, defaultUnit: Unit.G },
    { name: 'guacamole', category: IngredientCategory.PANTRY, defaultUnit: Unit.G },
    { name: 'mayonnaise', category: IngredientCategory.PANTRY, defaultUnit: Unit.TBSP },
    { name: 'ketchup', category: IngredientCategory.PANTRY, defaultUnit: Unit.TBSP },
    { name: 'sauce barbecue', category: IngredientCategory.PANTRY, defaultUnit: Unit.TBSP },
    { name: 'sauce worcestershire', category: IngredientCategory.PANTRY, defaultUnit: Unit.TBSP },
    { name: 'sauce fish', category: IngredientCategory.PANTRY, defaultUnit: Unit.TBSP },
    { name: 'nuoc mam', category: IngredientCategory.PANTRY, defaultUnit: Unit.TBSP },
    { name: 'sauce hoisin', category: IngredientCategory.PANTRY, defaultUnit: Unit.TBSP },
    { name: 'sauce aux huîtres', category: IngredientCategory.PANTRY, defaultUnit: Unit.TBSP },
    { name: 'sauce teriyaki', category: IngredientCategory.PANTRY, defaultUnit: Unit.TBSP },
    { name: 'pâte de miso', category: IngredientCategory.PANTRY, defaultUnit: Unit.TBSP },
    { name: 'wasabi', category: IngredientCategory.PANTRY, defaultUnit: Unit.TSP },
    { name: 'gingembre confit', category: IngredientCategory.PANTRY, defaultUnit: Unit.G },
    { name: 'pâte de curry', category: IngredientCategory.PANTRY, defaultUnit: Unit.TBSP },
    { name: 'pâte de tomate', category: IngredientCategory.PANTRY, defaultUnit: Unit.TBSP },
    { name: 'sauce tomate', category: IngredientCategory.PANTRY, defaultUnit: Unit.ML },
    { name: 'coulis de tomate', category: IngredientCategory.PANTRY, defaultUnit: Unit.ML },
    { name: 'purée de tomate', category: IngredientCategory.PANTRY, defaultUnit: Unit.G },
    { name: 'passata', category: IngredientCategory.PANTRY, defaultUnit: Unit.ML },
    { name: 'tomate en conserve', category: IngredientCategory.PANTRY, defaultUnit: Unit.G },
    { name: 'tomate pelée', category: IngredientCategory.PANTRY, defaultUnit: Unit.G },
    { name: 'concentré de tomate', category: IngredientCategory.PANTRY, defaultUnit: Unit.TBSP },
    { name: 'bouillon de légumes', category: IngredientCategory.PANTRY, defaultUnit: Unit.ML },
    { name: 'bouillon de poulet', category: IngredientCategory.PANTRY, defaultUnit: Unit.ML },
    { name: 'bouillon de boeuf', category: IngredientCategory.PANTRY, defaultUnit: Unit.ML },
    { name: 'bouillon de poisson', category: IngredientCategory.PANTRY, defaultUnit: Unit.ML },
    { name: 'fond de volaille', category: IngredientCategory.PANTRY, defaultUnit: Unit.ML },
    { name: 'fond de veau', category: IngredientCategory.PANTRY, defaultUnit: Unit.ML },
    { name: 'fond de gibier', category: IngredientCategory.PANTRY, defaultUnit: Unit.ML },
    { name: 'cube de bouillon', category: IngredientCategory.PANTRY, defaultUnit: Unit.PIECE },
    { name: 'glace de viande', category: IngredientCategory.PANTRY, defaultUnit: Unit.TBSP },

    // === CHOCOLAT ET CACAO ===
    { name: 'chocolat noir', category: IngredientCategory.PANTRY, defaultUnit: Unit.G },
    { name: 'chocolat au lait', category: IngredientCategory.PANTRY, defaultUnit: Unit.G },
    { name: 'chocolat blanc', category: IngredientCategory.PANTRY, defaultUnit: Unit.G },
    { name: 'cacao en poudre', category: IngredientCategory.PANTRY, defaultUnit: Unit.G },
    { name: 'pépites de chocolat', category: IngredientCategory.PANTRY, defaultUnit: Unit.G },
    { name: 'pâte à tartiner', category: IngredientCategory.PANTRY, defaultUnit: Unit.TBSP },
    { name: 'Nutella', category: IngredientCategory.PANTRY, defaultUnit: Unit.TBSP },

    // === AUTRES ===
    { name: 'gélatine', category: IngredientCategory.PANTRY, defaultUnit: Unit.G },
    { name: 'agar-agar', category: IngredientCategory.PANTRY, defaultUnit: Unit.G },
    { name: 'colle de poisson', category: IngredientCategory.PANTRY, defaultUnit: Unit.G },
    { name: 'eau', category: IngredientCategory.BEVERAGES, defaultUnit: Unit.ML },
    { name: 'glace', category: IngredientCategory.FROZEN, defaultUnit: Unit.G },
    { name: 'sel de Guérande', category: IngredientCategory.SPICES, defaultUnit: Unit.PINCH },
    { name: 'fleur de sel', category: IngredientCategory.SPICES, defaultUnit: Unit.PINCH },
    { name: 'gros sel', category: IngredientCategory.SPICES, defaultUnit: Unit.PINCH },
    { name: 'sel de mer', category: IngredientCategory.SPICES, defaultUnit: Unit.PINCH },
    { name: 'cristaux de sel', category: IngredientCategory.SPICES, defaultUnit: Unit.PINCH },
    
    // === INGRÉDIENTS SUPPLÉMENTAIRES POUR LES RECETTES ===
    { name: 'pousses de soja', category: IngredientCategory.FRESH, defaultUnit: Unit.G },
    { name: 'café fort', category: IngredientCategory.BEVERAGES, defaultUnit: Unit.ML },
    { name: 'biscuits à la cuillère', category: IngredientCategory.BAKERY, defaultUnit: Unit.PIECE },
    { name: 'cacao', category: IngredientCategory.PANTRY, defaultUnit: Unit.G },
    { name: 'olives', category: IngredientCategory.PANTRY, defaultUnit: Unit.G },
];

